In [71]:
## Scraping census code from american census' api in two lots (limit on how many fields can be extraced in a single api call) 
## In addition, this code is scraping crime data from city's opendata and joining it to the census data.
## US Census source: Community 5 year Survey: ACS/ACS5/Profile.html as it has percentages
## https://api.census.gov/data/2018/acs/acs5/profile/groups.html

## DP05_0071PE % hispanic or latino of any race  DP05_0077PE White not latino, DP05_0078PE black not hispanic or latino
## DP05_0080PE for Asians  
import requests
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)



HOST = "https://api.census.gov/data"
year = "2018"
dataset = "acs/acs5/profile.html" ## has census tract groups only; not census block groups 
key = "27d6154de64a12d9b06727be7177fe46e7c4eee1"
base_url = "/".join([HOST, year, dataset])

## ACS Detailed table request
get_vars = ["DP05_0001E","DP02_0001E", "DP02_0002E","DP02_0008PE", "DP02_0010PE", 
            "DP02_0015E", "DP02_0016E", "DP02_0022PE", "DP02_0038E", "DP02_0046PE",
            "DP02_0048PE","DP02_0060PE","DP02_0063PE","DP02_0079PE","DP02_0085PE",
            "DP02_0088PE","DP02_0112PE","DP02_0134PE",
            "DP03_0009PE","DP03_0027PE","DP03_0028PE","DP03_0037PE","DP03_0040PE",
            "DP03_0041PE","DP03_0050PE","DP03_0052PE", "DP03_0054PE","DP03_0058PE",
            "DP03_0061PE","DP03_0065E","DP03_0066PE","DP03_0072PE","DP03_0074PE",
            "DP03_0085PE","DP03_0092E","DP03_0093E","DP03_0094E",
            "DP03_0097PE","DP03_0097PE",
            "DP03_0099PE","DP03_0119PE","DP03_0121PE","DP03_0126PE","DP04_0001PE",
            "DP04_0002PE","DP04_0004E","DP04_0005E","DP04_0006E"] # total housing units  

get_vars = ["NAME"] + get_vars


dfs = []
items = ["005", "047", "059", "061", "081", "085", "119"]

for item in items:
    predicates = {}
    predicates["get"] = ",".join(get_vars)
    predicates["for"] = "tract:*"
    predicates["in"] = "state:36;county:"+item  ## Bronx, Brooklyn, MH, Queens and St. Island
    predicates["key"]="27d6154de64a12d9b06727be7177fe46e7c4eee1"
    r6 = requests.get(base_url, params=predicates)
    col_names = ["NAME", "DP05_0001E-T Popo","DP02_0001E-T HHs","DP02_0002E-T Fam HHs",
                 "DP02_0008PE-%F-led HHs No H","DP02_0010PE-% Non-Fam HHs", "DP02_0015E-Avg HH Size",
                 "DP02_0016E-Avg Fam Size", "DP02_0022PE-%Non Rel in Hs","DP02_0038E-per1000-F-U-RecentPreg", 
                 "DP02_0046PE-%GPwParent&Gc1-2yrs", "DP02_0048PE--%GPwParent&Gc>5yrs", "DP02_0060PE-%NoSchDiploma",
                 "DP02_0063PE-%AssDeg","DP02_0079PE-% SameHouse_1YrAgo","DP02_0085PE-%LivAbroad1YrAgo",
                 "DP02_0088PE-%BornUS", "DP02_0112PE-HomeLangNotEng", "DP02_0134PE-%IrishAnc", 
                 "DP03_0009PE-%Unemploy",
                 "DP03_0027PE-%WorkingMgt,Bus,Sc,Arts","DP03_0028PE%WorkingService","DP03_0037PE-Retail", 
                 "DP03_0040PE-%Fin&Ins","DP03_0041PE-%ProfSc,Mgt,Admin","DP03_0050PE-%UnpaidFamilyWk",
                 "DP03_0052PE-Inc<10k", "DP03_0054PE-Inc15-24k", "DP03_0058PE-Inc75-99k", "DP03_0061PE-Inc200k>",
                 "DP03_0065E-HH-MeanEarnings","DP03_0066PE-%HHsWithSocSec","DP03_0072PE-%HH Inc with Cash public Ass",
                 "DP03_0074PE-%HH Inc with Food Stamps SNAP","DP03_0085PE-%Families Inc>200k", 
                 "DP03_0092E-Median Earning Workers","DP03_0093E-Median Earnings Male FT Workers",
                 "DP03_0094E-Median Earnings Female FT Workers",
                 "DP03_0097PE-%PHI-Priv","DP03_0098PE-%PHI-Pub","DP03_0099PE-No PHI","DP03_0119PE-% Fam <Pov", 
                 "DP03_0121PE-%Fam with child U18&U5 <pov","DP03_0126PE-%F-Led Families with u18 <pov",
                 "DP04_0001E-T H U", "DP04_0002PE-%Occ H U","DP04_0004E-%Ow Vac Rate", "DP04_0005E-%Rn Vac Rate",
                 "DP04_0006E-T HU",
                 "State","County", "Tract"]
    print("county:", item)
    df_collect = pd.DataFrame(columns=col_names, data=r6.json()[1:])
    rows = len(df_collect)
    print("rows in r", rows)
    dfs.append(df_collect)

dc_NYC1 = pd.concat(dfs)            # examine the response

dc_NYC1.shape
from datetime import date
print("Today's date is:", date.today())
dc_NYC1.head()

county: 005
rows in r 339
county: 047
rows in r 761
county: 059
rows in r 284
county: 061
rows in r 288
county: 081
rows in r 669
county: 085
rows in r 110
county: 119
rows in r 223
Today's date is: 2021-02-21

,NAME,DP05_0001E-T Popo,DP02_0001E-T HHs,DP02_0002E-T Fam HHs,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0015E-Avg HH Size,DP02_0016E-Avg Fam Size,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0065E-HH-MeanEarnings,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0092E-Median Earning Workers,DP03_0093E-Median Earnings Male FT Workers,DP03_0094E-Median Earnings Female FT Workers,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0001E-T H U,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0006E-T HU,State,County,Tract
0,"Census Tract 429.02, Bronx County, New York",4205,1599,967,25.1,39.5,2.56,3.39,4.5,92,23.0,10.9,16.2,6.2,84.9,1.2,51.0,65.9,3.7,18.1,23.4,28.0,13.6,1.8,15.2,0.0,11.8,14.1,7.5,0.0,52789,18.7,18.9,44.7,0.0,21505,40850,28938,37.7,37.7,11.9,37.6,37.0,71.6,1647,97.1,0.0,2.1,1647,36,005,042902
1,"Census Tract 330, Bronx County, New York",5885,2129,1433,12.3,32.7,2.76,3.43,4.6,104,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,52566,18.0,5.1,35.5,0.0,27189,36468,31750,38.0,38.0,17.3,18.1,11.5,76.0,2238,95.1,0.0,3.5,2238,36,005,033000
2,"Census Tract 358, Bronx County, New York",8054,2443,1885,23.1,22.8,3.27,3.66,6.6,84,0.0,5.7,6.0,11.0,89.6,0.4,53.1,30.0,0.0,11.1,38.7,24.6,11.7,6.9,5.6,0.0,2.0,7.6,16.2,7.1,90805,35.2,0.0,15.5,8.4,32354,43970,41750,70.1,70.1,4.3,5.5,9.8,0.0,2551,95.8,1.6,3.5,2551,36,005,035800
3,"Census Tract 371, Bronx County, New York",4322,1739,888,20.2,48.9,2.46,3.68,3.8,54,4.8,0.0,19.6,5.1,94.0,1.2,55.5,67.3,0.8,7.2,10.5,41.1,17.2,7.1,4.8,0.0,13.5,13.1,5.2,1.5,61803,33.0,7.5,53.6,1.4,26262,52039,27763,40.8,40.8,6.2,24.2,0.0,29.4,1828,95.1,0.0,1.5,1828,36,005,037100
4,"Census Tract 385, Bronx County, New York",4757,1674,1028,38.9,38.6,2.80,3.75,4.0,49,0.0,17.6,23.1,7.0,90.5,0.9,61.7,67.9,0.4,13.2,10.6,46.2,15.7,3.1,7.7,0.0,25.1,17.1,3.1,0.8,36603,18.9,9.7,60.5,0.4,18641,24963,29083,21.8,21.8,16.8,44.6,55.0,59.5,1829,91.5,52.7,4.0,1829,36,005,038500

In [72]:
## other variables same as for dc_NYC1
## ACS Detailed table request
get_vars = ["DP04_0013PE","DP04_0017PE","DP04_0029PE","DP04_0039PE","DP04_0045PE", "DP04_0046PE",
           "DP04_0047E","DP04_0048E","DP04_0051PE", "DP04_0054PE", "DP04_0082PE","DP04_0083PE",
            "DP04_0084PE","DP04_0087PE","DP04_0101E", "DP04_0134E","DP05_0005PE","DP05_0023PE",
           "DP05_0059PE","DP05_0061PE","DP05_0064PE", "DP05_0070PE"]
get_vars = ["NAME"] + get_vars
dfs2 = []
for item in items:
    predicates = {}
    predicates["get"] = ",".join(get_vars)
    #predicates["for"] = "place:51000"
    #predicates["for"] = "county:005
    #predicates["in"] = "state:36"
    predicates["for"] = "tract:*"
    #predicates["in"] = "state:06;county:037;tract:*"  ## California, LA 
    predicates["in"] = "state:36;county:"+item  ## Bronx, Brooklyn, MH, Queens and St. Island
    predicates["key"]="27d6154de64a12d9b06727be7177fe46e7c4eee1"
    r7 = requests.get(base_url, params=predicates)
# print(' \n ', r3.text)
    col_names = ["NAME","DP04_0013PE-%20+HU","DP04_0017PE-%Built2014+", "DP04_0029PE-%2rooms_only_HU",
                 "DP04_0039PE-Zero bedrooms","DP04_0045PE-%Occup HU","DP04_0046PE-%Owner Occup HU",
                 "DP04_0048E-Owner Ave Household size","DP04_0049E-Renter Ave Household size",
                 "DP04_0051PE-%moved since 2017+","DP04_0054PE-%moved 2000 to 2009",
                 "DP04_0082PE-%Value 50-99k","DP04_0083PE-%Value 100-149k","DP04_0084PE-%Value 150-199k",
                 "DP04_0087PE-%Value 500k-1m","DP04_0101E-Med Onwer Monthly Mortgage",
                 "DP04_0134E-Median Gross Rent","DP05_0005PE-%under 5 yrs", "DP05_0023PE-%62 yrs+",
                 "DP05_0058PE-% w & B or AM","DP05_0061PE-%White & Asian","DP05_0064PE-%White with others",
                 "DP05_0070PE-%H&L race",
                 "State","County", "Tract"]
    print("county:", item)
    df_collect = pd.DataFrame(columns=col_names, data=r7.json()[1:])
    rows = len(df_collect)
    print("rows in r", rows)
    dfs2.append(df_collect)
#print('\n 2018 - NYC County Results = \n ',df6)
dc_NYC2 = pd.concat(dfs2)            # examine the response


dc_NYC2.shape

print("Today's date is:", date.today())
dc_NYC2.head()

county: 005
rows in r 339
county: 047
rows in r 761
county: 059
rows in r 284
county: 061
rows in r 288
county: 081
rows in r 669
county: 085
rows in r 110
county: 119
rows in r 223
Today's date is: 2021-02-21

                                          NAME DP04_0013PE-%20+HU DP04_0017PE-%Built2014+ DP04_0029PE-%2rooms_only_HU DP04_0039PE-Zero bedrooms DP04_0045PE-%Occup HU DP04_0046PE-%Owner Occup HU DP04_0048E-Owner Ave Household size DP04_0049E-Renter Ave Household size DP04_0051PE-%moved since 2017+ DP04_0054PE-%moved 2000 to 2009 DP04_0082PE-%Value 50-99k DP04_0083PE-%Value 100-149k DP04_0084PE-%Value 150-199k DP04_0087PE-%Value 500k-1m DP04_0101E-Med Onwer Monthly Mortgage DP04_0134E-Median Gross Rent DP05_0005PE-%under 5 yrs DP05_0023PE-%62 yrs+ DP05_0058PE-% w & B or AM DP05_0061PE-%White & Asian DP05_0064PE-%White with others DP05_0070PE-%H&L race State County   Tract
0  Census Tract 429.02, Bronx County, New York               77.2                     3.2                         4.4                       5.5                  1599                         9.8                                1442                                 2.05                            5.7                            23.0                      43.3                         0.0                         0.0                       14.0                                  3629                         1354                      9.9                 13.7                       2.3                        0.2                           14.0                  4205    36    005  042902
1     Census Tract 330, Bronx County, New York               66.9                     0.9                         1.2                      10.0                  2129                         4.9                                2024                                 3.32                            1.6                            46.6                      18.1                         0.0                         0.0                        5.7                            -666666666                         1206                      6.9                 15.8                       0.0                        0.0                           50.0                  5885    36    005  033000
2     Census Tract 358, Bronx County, New York                3.1                     0.0                         0.9                       2.9                  2443                        65.9                                 834                                 3.34                            1.9                            30.7                       1.1                         0.0                         0.0                       18.6                                  2817                         1431                      5.4                 19.0                       0.0                        0.0                           10.4                  8054    36    005  035800
3     Census Tract 371, Bronx County, New York               63.2                     0.0                         1.8                      19.9                  1739                        10.4                                1558                                 4.02                            3.5                            41.1                       0.0                         5.5                         0.0                       30.9                                  2301                          795                      6.2                 20.5                       1.1                        0.0                           27.3                  4322    36    005  037100
4     Census Tract 385, Bronx County, New York               72.9                     0.0                         4.4                      12.7                  1674                         1.6                                1648                                 2.19                            2.9                            26.7                      26.9                         0.0                         0.0                        0.0                                  2750                         1034                     12.4                 12.2                       0.2                        0.0                            8.3                  4757    36    005  038500

In [74]:
import pandas as pd
### join dc_NYC1 and dc_NYC2 
## Notes on joining - https://stackoverflow.com/questions/40468069/merge-two-dataframes-by-index
## Example from Nov 22nd NYC Census Blocks - df_NewYorkAll = pd.merge(left = df_NewYork, right = groupedTract_max_ALAND[['LandArea']], left_index=True, right_index=True)
#dc_NYCAll = pd.merge(left = dc_NYC, right = dc_NYC2, left_index=True, right_index=True) === doesn't work
dc_NYCAll = pd.merge(left = dc_NYC1, right = dc_NYC2, how = 'right', left_on = ['NAME','State','County','Tract'], right_on = ['NAME','State','County','Tract'])
    
#    how = 'right', left_on = 'County_TRACTCEandBLKGRPCE', right_on = 'Census_Block')
dc_NYCAll.head()

,NAME,DP05_0001E-T Popo,DP02_0001E-T HHs,DP02_0002E-T Fam HHs,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0015E-Avg HH Size,DP02_0016E-Avg Fam Size,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0065E-HH-MeanEarnings,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0092E-Median Earning Workers,DP03_0093E-Median Earnings Male FT Workers,DP03_0094E-Median Earnings Female FT Workers,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0001E-T H U,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0006E-T HU,State,County,Tract,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0045PE-%Occup HU,DP04_0046PE-%Owner Occup HU,DP04_0048E-Owner Ave Household size,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP04_0101E-Med Onwer Monthly Mortgage,DP04_0134E-Median Gross Rent,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,DP05_0070PE-%H&L race
0,"Census Tract 429.02, Bronx County, New York",4205,1599,967,25.1,39.5,2.56,3.39,4.5,92,23.0,10.9,16.2,6.2,84.9,1.2,51.0,65.9,3.7,18.1,23.4,28.0,13.6,1.8,15.2,0.0,11.8,14.1,7.5,0.0,52789,18.7,18.9,44.7,0.0,21505,40850,28938,37.7,37.7,11.9,37.6,37.0,71.6,1647,97.1,0.0,2.1,1647,36,005,042902,77.2,3.2,4.4,5.5,1599,9.8,1442,2.05,5.7,23.0,43.3,0.0,0.0,14.0,3629,1354,9.9,13.7,2.3,0.2,14.0,4205
1,"Census Tract 330, Bronx County, New York",5885,2129,1433,12.3,32.7,2.76,3.43,4.6,104,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,52566,18.0,5.1,35.5,0.0,27189,36468,31750,38.0,38.0,17.3,18.1,11.5,76.0,2238,95.1,0.0,3.5,2238,36,005,033000,66.9,0.9,1.2,10.0,2129,4.9,2024,3.32,1.6,46.6,18.1,0.0,0.0,5.7,-666666666,1206,6.9,15.8,0.0,0.0,50.0,5885
2,"Census Tract 358, Bronx County, New York",8054,2443,1885,23.1,22.8,3.27,3.66,6.6,84,0.0,5.7,6.0,11.0,89.6,0.4,53.1,30.0,0.0,11.1,38.7,24.6,11.7,6.9,5.6,0.0,2.0,7.6,16.2,7.1,90805,35.2,0.0,15.5,8.4,32354,43970,41750,70.1,70.1,4.3,5.5,9.8,0.0,2551,95.8,1.6,3.5,2551,36,005,035800,3.1,0.0,0.9,2.9,2443,65.9,834,3.34,1.9,30.7,1.1,0.0,0.0,18.6,2817,1431,5.4,19.0,0.0,0.0,10.4,8054
3,"Census Tract 371, Bronx County, New York",4322,1739,888,20.2,48.9,2.46,3.68,3.8,54,4.8,0.0,19.6,5.1,94.0,1.2,55.5,67.3,0.8,7.2,10.5,41.1,17.2,7.1,4.8,0.0,13.5,13.1,5.2,1.5,61803,33.0,7.5,53.6,1.4,26262,52039,27763,40.8,40.8,6.2,24.2,0.0,29.4,1828,95.1,0.0,1.5,1828,36,005,037100,63.2,0.0,1.8,19.9,1739,10.4,1558,4.02,3.5,41.1,0.0,5.5,0.0,30.9,2301,795,6.2,20.5,1.1,0.0,27.3,4322
4,"Census Tract 385, Bronx County, New York",4757,1674,1028,38.9,38.6,2.80,3.75,4.0,49,0.0,17.6,23.1,7.0,90.5,0.9,61.7,67.9,0.4,13.2,10.6,46.2,15.7,3.1,7.7,0.0,25.1,17.1,3.1,0.8,36603,18.9,9.7,60.5,0.4,18641,24963,29083,21.8,21.8,16.8,44.6,55.0,59.5,1829,91.5,52.7,4.0,1829,36,005,038500,72.9,0.0,4.4,12.7,1674,1.6,1648,2.19,2.9,26.7,26.9,0.0,0.0,0.0,2750,1034,12.4,12.2,0.2,0.0,8.3,4757

In [4]:
## Single file Feb 21st collating all NYC Census data and NY Crime 
## adding crime statistics to

In [4]:
## Scraping New York crime data
## json api https://data.cityofnewyork.us/resource/sv2w-rv3k.json

## website: https://data.cityofnewyork.us/Public-Safety/NYPD-Criminal-Court-Summons-Historic-/sv2w-rv3k  5.28m rows 21/2/2021 

import requests
import pandas as pd
#1ml retrieved
#data = requests.get('https://data.cityofnewyork.us/resource/sv2w-rv3k.json?$limit=1000000&$select=BORO,latitude,longitude').json()
#10k retrieved
data = requests.get('https://data.cityofnewyork.us/resource/sv2w-rv3k.json?$limit=5300000&$select=BORO,latitude,longitude').json()

##  CRS, WGS 1984, decimal degrees (EPSG 4326)

NYC_Crime_df = pd.DataFrame(data=data)
NYC_Crime_df.to_csv("NewYork_crime_as_downloaded_Feb21th2021.csv") ## 5.2m rows 21/2/2021
NYC_Crime_df.head()

       BORO            latitude            longitude
0  NEW YORK  40.763406514000053  -73.979028011999958
1  BROOKLYN  40.681362236000041  -73.975491630999954
2  BROOKLYN  40.657993066000074  -74.000693445999957
3    QUEENS  40.762980083000059  -73.831189714999937
4     BRONX  40.836689797000076  -73.928667417999975

In [5]:
NYC_Crime_df['longitude'].isnull().sum() ## there are None

##df = df[df['EPS'].notna()] to keep rows that have not got NAs

NYC_Crime_df = NYC_Crime_df[NYC_Crime_df['longitude'].notna()]
print("No of NYC NAs in longitude col", NYC_Crime_df['longitude'].isnull().sum())
print("shape of NYC_Crime_df", NYC_Crime_df.shape)  
NYC_Crime_df

No of NYC NAs in longitude col 0
shape of NYC_Crime_df (5280663, 3)

              BORO            latitude            longitude
0         NEW YORK  40.763406514000053  -73.979028011999958
1         BROOKLYN  40.681362236000041  -73.975491630999954
2         BROOKLYN  40.657993066000074  -74.000693445999957
3           QUEENS  40.762980083000059  -73.831189714999937
4            BRONX  40.836689797000076  -73.928667417999975
...            ...                 ...                  ...
5280670      BRONX   40.81314793300004        -73.908617511
5280671     QUEENS   40.73126046700002   -73.86570625399997
5280672   BROOKLYN   40.57640060600005   -73.98689464399997
5280673      BRONX   40.82666587600005        -73.873896614
5280674  MANHATTAN   40.82809640100004   -73.93874355299994

[5280663 rows x 3 columns]

In [19]:
import geopandas as gpd ## completing for tracts


nyc_data_points = gpd.GeoDataFrame(NYC_Crime_df, geometry=gpd.points_from_xy(NYC_Crime_df.longitude, NYC_Crime_df.latitude), crs='EPSG:4326')

nyc_shape = "cb_2018_36_tract_500k.shp"  # load shape file 

nyc_map = gpd.read_file(nyc_shape)

NYC_points_in_map = gpd.sjoin(nyc_data_points.to_crs('EPSG:4269'), 
                         nyc_map, 
                         how='inner', 
                         op='within')
print("I am done")
print("Today's date is:", date.today())

I am done
Today's date is: 2021-02-21

In [75]:
## notice that the NY's shape map doesn't give you tract, county and state columns, 
## as provided by other state shape files. It is an odd difference as naming convention is exactly the same for all state shape files.
## NY's shape file gives you the index_right column, and this is enough for project's purposes so it is not an issue. 
## 
## However, on Feb 21st, the NYC_points_in_map file has the State, county and tract columns, so not sure why
## this file didn't have it before. I notice that Chicago didn't have state, county and tract details in its points_in_map
##
## The dbf file does have the state, county and tract details which can be obtained using the index_right reference. 
NYC_points_in_map.head()

          BORO            latitude            longitude                    geometry  index_right State County   Tract              AFFGEOID        GEOID NAME LSAD  AreaLand  AWATER
0     NEW YORK  40.763406514000053  -73.979028011999958  POINT (-73.97903 40.76341)         1457    36    061  013700  1400000US36061013700  36061013700  137   CT    226356       0
78    NEW YORK  40.765343809000058  -73.976471527999934  POINT (-73.97647 40.76534)         1457    36    061  013700  1400000US36061013700  36061013700  137   CT    226356       0
140   NEW YORK  40.765343809000058  -73.976471527999934  POINT (-73.97647 40.76534)         1457    36    061  013700  1400000US36061013700  36061013700  137   CT    226356       0
453   NEW YORK  40.763406514000053  -73.979028011999958  POINT (-73.97903 40.76341)         1457    36    061  013700  1400000US36061013700  36061013700  137   CT    226356       0
1613  NEW YORK  40.763406514000053  -73.979028011999958  POINT (-73.97903 40.76341)         1457    36    061  013700  1400000US36061013700  36061013700  137   CT    226356       0

In [114]:
## opened a copy of cb_2018_36_tract_500k.dbf in Excel and save as a csv file. (36 is code for New York)
## the index_right gives aligns with index in csv file. 
import pandas as pd
census_tract_NYC = pd.read_csv("cb_2018_36_tract_500k.csv", header=0)
print("census tract info from New York dbf file saved as a csv file on", date.today())
census_tract_NYC[1:2]

census tract info from New York dbf file saved as a csv file on 2021-02-21

   STATEFP  COUNTYFP  TRACTCE              AFFGEOID        GEOID  NAME LSAD     ALAND   AWATER
1       36        21      402  1400000US36021000402  36021000402  4.02   CT  42294908  1437327

In [115]:
## https://stackoverflow.com/questions/23836277/add-leading-zeros-to-strings-in-pandas-dataframe 
census_tract_NYC['COUNTYFP'] = census_tract_NYC['COUNTYFP'].apply(lambda x: '{0:0>3}'.format(x)).astype(str)
census_tract_NYC['TRACTCE'] = census_tract_NYC['TRACTCE'].apply(lambda x: '{0:0>6}'.format(x)).astype(str)
census_tract_NYC['STATEFP'] = census_tract_NYC['STATEFP'].apply(lambda x: '{0:0>2}'.format(x)).astype(str).astype(str)

In [116]:
census_tract_NYC[1:2]

  STATEFP COUNTYFP TRACTCE              AFFGEOID        GEOID  NAME LSAD     ALAND   AWATER
1      36      021  000402  1400000US36021000402  36021000402  4.02   CT  42294908  1437327

In [117]:
## Checking what county are listed in the crime data as this is what 
## is needed when extracting from census
list = NYC_points_in_map['County'].unique() ## checking if leading zeros needed 
list[0:10,] ## so extracted from correct census counties as this shows only 031 and 043.

array(['061', '047', '081', '005', '085', '119', '059'], dtype=object)

In [118]:
NYC_points_in_map.head()

          BORO            latitude            longitude                    geometry  index_right State County   Tract              AFFGEOID        GEOID NAME LSAD  AreaLand  AWATER
0     NEW YORK  40.763406514000053  -73.979028011999958  POINT (-73.97903 40.76341)         1457    36    061  013700  1400000US36061013700  36061013700  137   CT    226356       0
78    NEW YORK  40.765343809000058  -73.976471527999934  POINT (-73.97647 40.76534)         1457    36    061  013700  1400000US36061013700  36061013700  137   CT    226356       0
140   NEW YORK  40.765343809000058  -73.976471527999934  POINT (-73.97647 40.76534)         1457    36    061  013700  1400000US36061013700  36061013700  137   CT    226356       0
453   NEW YORK  40.763406514000053  -73.979028011999958  POINT (-73.97903 40.76341)         1457    36    061  013700  1400000US36061013700  36061013700  137   CT    226356       0
1613  NEW YORK  40.763406514000053  -73.979028011999958  POINT (-73.97903 40.76341)         1457    36    061  013700  1400000US36061013700  36061013700  137   CT    226356       0

In [82]:
NYC_points_in_map.rename(columns={'STATEFP':'State', 'COUNTYFP': 'County', 'TRACTCE':'Tract', 'ALAND': 'AreaLand'}, inplace=True)

In [83]:
NYC_points_in_map['County'] = NYC_points_in_map['County'].apply(lambda x: '{0:0>3}'.format(x)).astype(str)
NYC_points_in_map['Tract'] = NYC_points_in_map['Tract'].apply(lambda x: '{0:0>6}'.format(x)).astype(str)
NYC_points_in_map['State'] = NYC_points_in_map['State'].apply(lambda x: '{0:0>2}'.format(x)).astype(str).astype(str)

In [84]:
NYC_points_in_map.head()

          BORO            latitude            longitude                    geometry  index_right State County   Tract              AFFGEOID        GEOID NAME LSAD  AreaLand  AWATER
0     NEW YORK  40.763406514000053  -73.979028011999958  POINT (-73.97903 40.76341)         1457    36    061  013700  1400000US36061013700  36061013700  137   CT    226356       0
78    NEW YORK  40.765343809000058  -73.976471527999934  POINT (-73.97647 40.76534)         1457    36    061  013700  1400000US36061013700  36061013700  137   CT    226356       0
140   NEW YORK  40.765343809000058  -73.976471527999934  POINT (-73.97647 40.76534)         1457    36    061  013700  1400000US36061013700  36061013700  137   CT    226356       0
453   NEW YORK  40.763406514000053  -73.979028011999958  POINT (-73.97903 40.76341)         1457    36    061  013700  1400000US36061013700  36061013700  137   CT    226356       0
1613  NEW YORK  40.763406514000053  -73.979028011999958  POINT (-73.97903 40.76341)         1457    36    061  013700  1400000US36061013700  36061013700  137   CT    226356       0

In [85]:
groupedTract_count = NYC_points_in_map.groupby(['County','Tract','AreaLand']).size().reset_index(name='crimeStats')
#df2 = df.rename({'a': 'X', 'b': 'Y'}, axis=1) 
groupedTract_count

     County   Tract  AreaLand  crimeStats
0       005  000200    479463         537
1       005  000400    770689         577
2       005  001600    485079         972
3       005  001900   1668013        6269
4       005  002000    395564        5435
...     ...     ...       ...         ...
2173    119  001503    775771           1
2174    119  002600   1471967          10
2175    119  002900    368883           4
2176    119  003000    358706           2
2177    119  005500   3490858          14

[2178 rows x 4 columns]

In [86]:
groupedTract_mean = groupedTract_count["crimeStats"].mean()
print("mean",groupedTract_mean)
groupedTract_min = groupedTract_count["crimeStats"].min()
print("min", groupedTract_min)
groupedTract_max = groupedTract_count["crimeStats"].max()
print("max", groupedTract_max)

mean 2424.185950413223
min 1
max 66178

In [87]:
import numpy as np
groupedTract_count["crime"] = np.where(groupedTract_count.crimeStats < groupedTract_mean, "low", "high")
groupedTract_count

     County   Tract  AreaLand  crimeStats crime
0       005  000200    479463         537   low
1       005  000400    770689         577   low
2       005  001600    485079         972   low
3       005  001900   1668013        6269  high
4       005  002000    395564        5435  high
...     ...     ...       ...         ...   ...
2173    119  001503    775771           1   low
2174    119  002600   1471967          10   low
2175    119  002900    368883           4   low
2176    119  003000    358706           2   low
2177    119  005500   3490858          14   low

[2178 rows x 5 columns]

In [88]:
####dc_NYCAll_withCrime.loc[dc_NYCAll_withCrime.crime == 0, 'crime'].count()
groupedTract_count.loc[groupedTract_count.crimeStats == 0, 'crimeStats'].count()

0

In [89]:
groupedTract_count.loc[groupedTract_count.AreaLand == 0, 'AreaLand'].count()

0

In [90]:
dc_NYCAll.dtypes

NAME                                            object
DP05_0001E-T Popo                               object
DP02_0001E-T HHs                                object
DP02_0002E-T Fam HHs                            object
DP02_0008PE-%F-led HHs No H                     object
DP02_0010PE-% Non-Fam HHs                       object
DP02_0015E-Avg HH Size                          object
DP02_0016E-Avg Fam Size                         object
DP02_0022PE-%Non Rel in Hs                      object
DP02_0038E-per1000-F-U-RecentPreg               object
DP02_0046PE-%GPwParent&Gc1-2yrs                 object
DP02_0048PE--%GPwParent&Gc>5yrs                 object
DP02_0060PE-%NoSchDiploma                       object
DP02_0063PE-%AssDeg                             object
DP02_0079PE-% SameHouse_1YrAgo                  object
DP02_0085PE-%LivAbroad1YrAgo                    object
DP02_0088PE-%BornUS                             object
DP02_0112PE-HomeLangNotEng                      object
DP02_0134PE-%IrishAnc                           object
DP03_0009PE-%Unemploy                           object
DP03_0027PE-%WorkingMgt,Bus,Sc,Arts             object
DP03_0028PE%WorkingService                      object
DP03_0037PE-Retail                              object
DP03_0040PE-%Fin&Ins                            object
DP03_0041PE-%ProfSc,Mgt,Admin                   object
DP03_0050PE-%UnpaidFamilyWk                     object
DP03_0052PE-Inc<10k                             object
DP03_0054PE-Inc15-24k                           object
DP03_0058PE-Inc75-99k                           object
DP03_0061PE-Inc200k>                            object
DP03_0065E-HH-MeanEarnings                      object
DP03_0066PE-%HHsWithSocSec                      object
DP03_0072PE-%HH Inc with Cash public Ass        object
DP03_0074PE-%HH Inc with Food Stamps SNAP       object
DP03_0085PE-%Families Inc>200k                  object
DP03_0092E-Median Earning Workers               object
DP03_0093E-Median Earnings Male FT Workers      object
DP03_0094E-Median Earnings Female FT Workers    object
DP03_0097PE-%PHI-Priv                           object
DP03_0098PE-%PHI-Pub                            object
DP03_0099PE-No PHI                              object
DP03_0119PE-% Fam <Pov                          object
DP03_0121PE-%Fam with child U18&U5 <pov         object
DP03_0126PE-%F-Led Families with u18 <pov       object
DP04_0001E-T H U                                object
DP04_0002PE-%Occ H U                            object
DP04_0004E-%Ow Vac Rate                         object
DP04_0005E-%Rn Vac Rate                         object
DP04_0006E-T HU                                 object
State                                           object
County                                          object
Tract                                           object
DP04_0013PE-%20+HU                              object
DP04_0017PE-%Built2014+                         object
DP04_0029PE-%2rooms_only_HU                     object
DP04_0039PE-Zero bedrooms                       object
DP04_0045PE-%Occup HU                           object
DP04_0046PE-%Owner Occup HU                     object
DP04_0048E-Owner Ave Household size             object
DP04_0049E-Renter Ave Household size            object
DP04_0051PE-%moved since 2017+                  object
DP04_0054PE-%moved 2000 to 2009                 object
DP04_0082PE-%Value 50-99k                       object
DP04_0083PE-%Value 100-149k                     object
DP04_0084PE-%Value 150-199k                     object
DP04_0087PE-%Value 500k-1m                      object
DP04_0101E-Med Onwer Monthly Mortgage           object
DP04_0134E-Median Gross Rent                    object
DP05_0005PE-%under 5 yrs                        object
DP05_0023PE-%62 yrs+                            object
DP05_0058PE-% w & B or AM                       object
DP05_0061PE-%White & Asian                      object
DP05_0064PE-%White with others                  object
DP05_0070PE-%H&L race                           object
dtype: object

In [91]:
## join census data to crime data 
## https://kodlogs.com/38097/len-left_on-must-equal-the-number-of-levels-in-the-index-of-right#:~:text=pages%20in%20html-,Len(left_on)%20must%20equal%20the%20number%20of%20levels%20in,the%20index%20of%20%22right%22.
#dc_NYCAll_withCrime = pd.merge(left = dc_NYCAll, right = groupedTract_count, how = 'inner', on = ['County', 'Tract'] )
dc_NYCAll_withCrime = pd.merge(left = dc_NYCAll, right = groupedTract_count, how = 'inner', on = ['County', 'Tract'] )

In [92]:
dc_NYCAll_withCrime.head()

,NAME,DP05_0001E-T Popo,DP02_0001E-T HHs,DP02_0002E-T Fam HHs,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0015E-Avg HH Size,DP02_0016E-Avg Fam Size,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0065E-HH-MeanEarnings,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0092E-Median Earning Workers,DP03_0093E-Median Earnings Male FT Workers,DP03_0094E-Median Earnings Female FT Workers,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0001E-T H U,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0006E-T HU,State,County,Tract,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0045PE-%Occup HU,DP04_0046PE-%Owner Occup HU,DP04_0048E-Owner Ave Household size,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP04_0101E-Med Onwer Monthly Mortgage,DP04_0134E-Median Gross Rent,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,DP05_0070PE-%H&L race,AreaLand,crimeStats,crime
0,"Census Tract 429.02, Bronx County, New York",4205,1599,967,25.1,39.5,2.56,3.39,4.5,92,23.0,10.9,16.2,6.2,84.9,1.2,51.0,65.9,3.7,18.1,23.4,28.0,13.6,1.8,15.2,0.0,11.8,14.1,7.5,0.0,52789,18.7,18.9,44.7,0.0,21505,40850,28938,37.7,37.7,11.9,37.6,37.0,71.6,1647,97.1,0.0,2.1,1647,36,005,042902,77.2,3.2,4.4,5.5,1599,9.8,1442,2.05,5.7,23.0,43.3,0.0,0.0,14.0,3629,1354,9.9,13.7,2.3,0.2,14.0,4205,94576,901,low
1,"Census Tract 330, Bronx County, New York",5885,2129,1433,12.3,32.7,2.76,3.43,4.6,104,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,52566,18.0,5.1,35.5,0.0,27189,36468,31750,38.0,38.0,17.3,18.1,11.5,76.0,2238,95.1,0.0,3.5,2238,36,005,033000,66.9,0.9,1.2,10.0,2129,4.9,2024,3.32,1.6,46.6,18.1,0.0,0.0,5.7,-666666666,1206,6.9,15.8,0.0,0.0,50.0,5885,206129,2490,high
2,"Census Tract 358, Bronx County, New York",8054,2443,1885,23.1,22.8,3.27,3.66,6.6,84,0.0,5.7,6.0,11.0,89.6,0.4,53.1,30.0,0.0,11.1,38.7,24.6,11.7,6.9,5.6,0.0,2.0,7.6,16.2,7.1,90805,35.2,0.0,15.5,8.4,32354,43970,41750,70.1,70.1,4.3,5.5,9.8,0.0,2551,95.8,1.6,3.5,2551,36,005,035800,3.1,0.0,0.9,2.9,2443,65.9,834,3.34,1.9,30.7,1.1,0.0,0.0,18.6,2817,1431,5.4,19.0,0.0,0.0,10.4,8054,651471,1667,low
3,"Census Tract 371, Bronx County, New York",4322,1739,888,20.2,48.9,2.46,3.68,3.8,54,4.8,0.0,19.6,5.1,94.0,1.2,55.5,67.3,0.8,7.2,10.5,41.1,17.2,7.1,4.8,0.0,13.5,13.1,5.2,1.5,61803,33.0,7.5,53.6,1.4,26262,52039,27763,40.8,40.8,6.2,24.2,0.0,29.4,1828,95.1,0.0,1.5,1828,36,005,037100,63.2,0.0,1.8,19.9,1739,10.4,1558,4.02,3.5,41.1,0.0,5.5,0.0,30.9,2301,795,6.2,20.5,1.1,0.0,27.3,4322,198178,2504,high
4,"Census Tract 385, Bronx County, New York",4757,1674,1028,38.9,38.6,2.80,3.75,4.0,49,0.0,17.6,23.1,7.0,90.5,0.9,61.7,67.9,0.4,13.2,10.6,46.2,15.7,3.1,7.7,0.0,25.1,17.1,3.1,0.8,36603,18.9,9.7,60.5,0.4,18641,24963,29083,21.8,21.8,16.8,44.6,55.0,59.5,1829,91.5,52.7,4.0,1829,36,005,038500,72.9,0.0,4.4,12.7,1674,1.6,1648,2.19,2.9,26.7,26.9,0.0,0.0,0.0,2750,1034,12.4,12.2,0.2,0.0,8.3,4757,189195,3443,high

In [93]:
print("dc_NYCAll_withCrime.shape", dc_NYCAll_withCrime.shape) ## interesting if done with a filter on counties you get 2168 which
## which matches the list Tim Geography dept at US Census sent me at end of Oct 2020. 
## used this to filter by counties https://stackoverflow.com/questions/12096252/use-a-list-of-values-to-select-rows-from-a-pandas-dataframe

dc_NYCAll_withCrime.shape (2178, 77)

In [94]:
dc_NYCAll_withCrime.isnull().sum().sum()

0

In [96]:
dc_NYCAll_withCrime['AreaLand'].head()

0     94576
1    206129
2    651471
3    198178
4    189195
Name: AreaLand, dtype: int64

In [97]:
dc_NYCAll_withCrime['ALAND'] = dc_NYCAll_withCrime['AreaLand']
dc_NYCAll_withCrime['AreaLand'] = (dc_NYCAll_withCrime['AreaLand']/10000).astype(int)

In [98]:
dc_NYCAll_withCrime['Popo_Density_Per_Hector'] = dc_NYCAll_withCrime['AreaLand']/(dc_NYCAll_withCrime['DP05_0001E-T Popo'].astype(int))

In [99]:
dc_NYCAll_withCrime['Popo_Density_Per_Hector'] = dc_NYCAll_withCrime['Popo_Density_Per_Hector'].round(4)

In [100]:
dc_NYCAll_withCrime['Popo_Density_Per_Hector']

0       0.0021
1       0.0034
2       0.0081
3       0.0044
4       0.0038
         ...
2173    0.0137
2174    0.0342
2175    0.0106
2176    0.0099
2177    0.0271
Name: Popo_Density_Per_Hector, Length: 2178, dtype: float64

In [101]:
dc_NYCAll_withCrime[dc_NYCAll_withCrime['DP05_0001E-T Popo']== 0]

Empty DataFrame
Columns: [NAME, DP05_0001E-T Popo, DP02_0001E-T HHs, DP02_0002E-T Fam HHs, DP02_0008PE-%F-led HHs No H, DP02_0010PE-% Non-Fam HHs, DP02_0015E-Avg HH Size, DP02_0016E-Avg Fam Size, DP02_0022PE-%Non Rel in Hs, DP02_0038E-per1000-F-U-RecentPreg, DP02_0046PE-%GPwParent&Gc1-2yrs, DP02_0048PE--%GPwParent&Gc>5yrs, DP02_0060PE-%NoSchDiploma, DP02_0063PE-%AssDeg, DP02_0079PE-% SameHouse_1YrAgo, DP02_0085PE-%LivAbroad1YrAgo, DP02_0088PE-%BornUS, DP02_0112PE-HomeLangNotEng, DP02_0134PE-%IrishAnc, DP03_0009PE-%Unemploy, DP03_0027PE-%WorkingMgt,Bus,Sc,Arts, DP03_0028PE%WorkingService, DP03_0037PE-Retail, DP03_0040PE-%Fin&Ins, DP03_0041PE-%ProfSc,Mgt,Admin, DP03_0050PE-%UnpaidFamilyWk, DP03_0052PE-Inc<10k, DP03_0054PE-Inc15-24k, DP03_0058PE-Inc75-99k, DP03_0061PE-Inc200k>, DP03_0065E-HH-MeanEarnings, DP03_0066PE-%HHsWithSocSec, DP03_0072PE-%HH Inc with Cash public Ass, DP03_0074PE-%HH Inc with Food Stamps SNAP, DP03_0085PE-%Families Inc>200k, DP03_0092E-Median Earning Workers, DP03_0093E-Median Earnings Male FT Workers, DP03_0094E-Median Earnings Female FT Workers, DP03_0097PE-%PHI-Priv, DP03_0098PE-%PHI-Pub, DP03_0099PE-No PHI, DP03_0119PE-% Fam <Pov, DP03_0121PE-%Fam with child U18&U5 <pov, DP03_0126PE-%F-Led Families with u18 <pov, DP04_0001E-T H U, DP04_0002PE-%Occ H U, DP04_0004E-%Ow Vac Rate, DP04_0005E-%Rn Vac Rate, DP04_0006E-T HU, State, County, Tract, DP04_0013PE-%20+HU, DP04_0017PE-%Built2014+, DP04_0029PE-%2rooms_only_HU, DP04_0039PE-Zero bedrooms, DP04_0045PE-%Occup HU, DP04_0046PE-%Owner Occup HU, DP04_0048E-Owner Ave Household size, DP04_0049E-Renter Ave Household size, DP04_0051PE-%moved since 2017+, DP04_0054PE-%moved 2000 to 2009, DP04_0082PE-%Value 50-99k, DP04_0083PE-%Value 100-149k, DP04_0084PE-%Value 150-199k, DP04_0087PE-%Value 500k-1m, DP04_0101E-Med Onwer Monthly Mortgage, DP04_0134E-Median Gross Rent, DP05_0005PE-%under 5 yrs, DP05_0023PE-%62 yrs+, DP05_0058PE-% w & B or AM, DP05_0061PE-%White & Asian, DP05_0064PE-%White with others, DP05_0070PE-%H&L race, AreaLand, crimeStats, crime, ALAND, Popo_Density_Per_Hector]
Index: []

In [102]:
dc_NYCAll_withCrime[dc_NYCAll_withCrime['DP05_0001E-T Popo'] == '0']

,NAME,DP05_0001E-T Popo,DP02_0001E-T HHs,DP02_0002E-T Fam HHs,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0015E-Avg HH Size,DP02_0016E-Avg Fam Size,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0065E-HH-MeanEarnings,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0092E-Median Earning Workers,DP03_0093E-Median Earnings Male FT Workers,DP03_0094E-Median Earnings Female FT Workers,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0001E-T H U,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0006E-T HU,State,County,Tract,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0045PE-%Occup HU,DP04_0046PE-%Owner Occup HU,DP04_0048E-Owner Ave Household size,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP04_0101E-Med Onwer Monthly Mortgage,DP04_0134E-Median Gross Rent,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,DP05_0070PE-%H&L race,AreaLand,crimeStats,crime,ALAND,Popo_Density_Per_Hector
78,"Census Tract 163, Bronx County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,-666666666.0,-666666666.0,0,36,005,016300,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,58,4789,high,586016,inf
82,"Census Tract 249, Bronx County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,-666666666.0,-666666666.0,0,36,005,024900,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,17,257,low,173728,inf
154,"Census Tract 171, Bronx County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,-666666666.0,-666666666.0,0,36,005,017100,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,17,2131,low,174589,inf
307,"Census Tract 110, Bronx County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,-666666666.0,-666666666.0,0,36,005,011000,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,206,645,low,2069297,inf
417,"Census Tract 407, Kings County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,-666666666.0,-666666666.0,0,36,047,040700,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,50,208,low,504834,inf
433,"Census Tract 177, Kings County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,-666666666.0,-666666666.0,0,36,047,017700,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,231,7956,high,2313042,inf
449,"Census Tract 1180, Kings County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,-666666666.0,-666666666.0,0,36,047,118000,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,75,3480,high,751605,inf
551,"Census Tract 960, Kings County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,-666666666.0,-666666666.0,0,36,047,096000,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,42,1120,low,423887,inf
686,"Census Tract 175, Kings County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,-666666666.0,-666666666.0,0,36,047,017500,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,196,568,low,1961397,inf
741,"Census Tract 154, Kings County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,-666666666.0,-666666666.0,0,36,047,015400,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,92,159,low,922940,inf
904,"Census Tract 852, Kings County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,-666666666.0,-666666666.0,0,36,047,085200,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,39,86,low,395710,inf
924,"Census Tract 86, Kings County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,-666666666.0,-666666666.0,0,36,047,008600,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,11,2225,low,113543,inf
965,"Census Tract 666, Kings County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,-666666666.0,-666666666.0,0,36,047,066600,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,404,1210,low,4047419,inf
1111,"Census Tract 86.02, New York County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,-666666666.0,-666666666.0,0,36,061,008602,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,10,945,low,106753,inf
1232,"Census Tract 1, New York County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,-666666666.0,-666666666.0,0,36,061,000100,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,7,13,low,77654,inf
1363,"Census Tract 311, New York County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,-666666666.0,-666666666.0,0,36,061,031100,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,73,241,low,730774,inf
1367,"Census Tract 319, New York County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,-666666666.0,-666666666.0,0,36,061,031900,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,9,233,low,99774,inf
1375,"Census Tract 5, New York County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,41,0.0,-666666666.0,-666666666.0,41,36,061,000500,100.0,0.0,0.0,0.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,84,9,low,843918,inf
1400,"Census Tract 171, Queens County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,-666666666.0,-666666666.0,0,36,081,017100,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,124,1244,low,1248954,inf
1420,"Census Tract 716, Queens County, New York",0,0,0,-666666666.0,-666666666.0,-666666666.00,-666666666.00,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,-666666666.0,-666666666.0,0,36,081,071600,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,-666666666.0,0,-666666666.00,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666,-666666666,-666666666.0,-666666666.0,-666666666.0,-666666666.0,-666666666.0,0,1831,45,low,18319107,inf

In [103]:
## double checking that there are no rows with zero popo, and there were '9'
dc_NYCAll_withCrime = dc_NYCAll_withCrime[dc_NYCAll_withCrime['DP05_0001E-T Popo'] != '0']

In [104]:
dc_NYCAll_withCrime.head()

,NAME,DP05_0001E-T Popo,DP02_0001E-T HHs,DP02_0002E-T Fam HHs,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0015E-Avg HH Size,DP02_0016E-Avg Fam Size,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0065E-HH-MeanEarnings,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0092E-Median Earning Workers,DP03_0093E-Median Earnings Male FT Workers,DP03_0094E-Median Earnings Female FT Workers,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0001E-T H U,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0006E-T HU,State,County,Tract,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0045PE-%Occup HU,DP04_0046PE-%Owner Occup HU,DP04_0048E-Owner Ave Household size,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP04_0101E-Med Onwer Monthly Mortgage,DP04_0134E-Median Gross Rent,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,DP05_0070PE-%H&L race,AreaLand,crimeStats,crime,ALAND,Popo_Density_Per_Hector
0,"Census Tract 429.02, Bronx County, New York",4205,1599,967,25.1,39.5,2.56,3.39,4.5,92,23.0,10.9,16.2,6.2,84.9,1.2,51.0,65.9,3.7,18.1,23.4,28.0,13.6,1.8,15.2,0.0,11.8,14.1,7.5,0.0,52789,18.7,18.9,44.7,0.0,21505,40850,28938,37.7,37.7,11.9,37.6,37.0,71.6,1647,97.1,0.0,2.1,1647,36,005,042902,77.2,3.2,4.4,5.5,1599,9.8,1442,2.05,5.7,23.0,43.3,0.0,0.0,14.0,3629,1354,9.9,13.7,2.3,0.2,14.0,4205,9,901,low,94576,0.0021
1,"Census Tract 330, Bronx County, New York",5885,2129,1433,12.3,32.7,2.76,3.43,4.6,104,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,52566,18.0,5.1,35.5,0.0,27189,36468,31750,38.0,38.0,17.3,18.1,11.5,76.0,2238,95.1,0.0,3.5,2238,36,005,033000,66.9,0.9,1.2,10.0,2129,4.9,2024,3.32,1.6,46.6,18.1,0.0,0.0,5.7,-666666666,1206,6.9,15.8,0.0,0.0,50.0,5885,20,2490,high,206129,0.0034
2,"Census Tract 358, Bronx County, New York",8054,2443,1885,23.1,22.8,3.27,3.66,6.6,84,0.0,5.7,6.0,11.0,89.6,0.4,53.1,30.0,0.0,11.1,38.7,24.6,11.7,6.9,5.6,0.0,2.0,7.6,16.2,7.1,90805,35.2,0.0,15.5,8.4,32354,43970,41750,70.1,70.1,4.3,5.5,9.8,0.0,2551,95.8,1.6,3.5,2551,36,005,035800,3.1,0.0,0.9,2.9,2443,65.9,834,3.34,1.9,30.7,1.1,0.0,0.0,18.6,2817,1431,5.4,19.0,0.0,0.0,10.4,8054,65,1667,low,651471,0.0081
3,"Census Tract 371, Bronx County, New York",4322,1739,888,20.2,48.9,2.46,3.68,3.8,54,4.8,0.0,19.6,5.1,94.0,1.2,55.5,67.3,0.8,7.2,10.5,41.1,17.2,7.1,4.8,0.0,13.5,13.1,5.2,1.5,61803,33.0,7.5,53.6,1.4,26262,52039,27763,40.8,40.8,6.2,24.2,0.0,29.4,1828,95.1,0.0,1.5,1828,36,005,037100,63.2,0.0,1.8,19.9,1739,10.4,1558,4.02,3.5,41.1,0.0,5.5,0.0,30.9,2301,795,6.2,20.5,1.1,0.0,27.3,4322,19,2504,high,198178,0.0044
4,"Census Tract 385, Bronx County, New York",4757,1674,1028,38.9,38.6,2.80,3.75,4.0,49,0.0,17.6,23.1,7.0,90.5,0.9,61.7,67.9,0.4,13.2,10.6,46.2,15.7,3.1,7.7,0.0,25.1,17.1,3.1,0.8,36603,18.9,9.7,60.5,0.4,18641,24963,29083,21.8,21.8,16.8,44.6,55.0,59.5,1829,91.5,52.7,4.0,1829,36,005,038500,72.9,0.0,4.4,12.7,1674,1.6,1648,2.19,2.9,26.7,26.9,0.0,0.0,0.0,2750,1034,12.4,12.2,0.2,0.0,8.3,4757,18,3443,high,189195,0.0038

In [105]:
dc_NYCAll_withCrime.head()

,NAME,DP05_0001E-T Popo,DP02_0001E-T HHs,DP02_0002E-T Fam HHs,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0015E-Avg HH Size,DP02_0016E-Avg Fam Size,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0065E-HH-MeanEarnings,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0092E-Median Earning Workers,DP03_0093E-Median Earnings Male FT Workers,DP03_0094E-Median Earnings Female FT Workers,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0001E-T H U,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0006E-T HU,State,County,Tract,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0045PE-%Occup HU,DP04_0046PE-%Owner Occup HU,DP04_0048E-Owner Ave Household size,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP04_0101E-Med Onwer Monthly Mortgage,DP04_0134E-Median Gross Rent,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,DP05_0070PE-%H&L race,AreaLand,crimeStats,crime,ALAND,Popo_Density_Per_Hector
0,"Census Tract 429.02, Bronx County, New York",4205,1599,967,25.1,39.5,2.56,3.39,4.5,92,23.0,10.9,16.2,6.2,84.9,1.2,51.0,65.9,3.7,18.1,23.4,28.0,13.6,1.8,15.2,0.0,11.8,14.1,7.5,0.0,52789,18.7,18.9,44.7,0.0,21505,40850,28938,37.7,37.7,11.9,37.6,37.0,71.6,1647,97.1,0.0,2.1,1647,36,005,042902,77.2,3.2,4.4,5.5,1599,9.8,1442,2.05,5.7,23.0,43.3,0.0,0.0,14.0,3629,1354,9.9,13.7,2.3,0.2,14.0,4205,9,901,low,94576,0.0021
1,"Census Tract 330, Bronx County, New York",5885,2129,1433,12.3,32.7,2.76,3.43,4.6,104,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,52566,18.0,5.1,35.5,0.0,27189,36468,31750,38.0,38.0,17.3,18.1,11.5,76.0,2238,95.1,0.0,3.5,2238,36,005,033000,66.9,0.9,1.2,10.0,2129,4.9,2024,3.32,1.6,46.6,18.1,0.0,0.0,5.7,-666666666,1206,6.9,15.8,0.0,0.0,50.0,5885,20,2490,high,206129,0.0034
2,"Census Tract 358, Bronx County, New York",8054,2443,1885,23.1,22.8,3.27,3.66,6.6,84,0.0,5.7,6.0,11.0,89.6,0.4,53.1,30.0,0.0,11.1,38.7,24.6,11.7,6.9,5.6,0.0,2.0,7.6,16.2,7.1,90805,35.2,0.0,15.5,8.4,32354,43970,41750,70.1,70.1,4.3,5.5,9.8,0.0,2551,95.8,1.6,3.5,2551,36,005,035800,3.1,0.0,0.9,2.9,2443,65.9,834,3.34,1.9,30.7,1.1,0.0,0.0,18.6,2817,1431,5.4,19.0,0.0,0.0,10.4,8054,65,1667,low,651471,0.0081
3,"Census Tract 371, Bronx County, New York",4322,1739,888,20.2,48.9,2.46,3.68,3.8,54,4.8,0.0,19.6,5.1,94.0,1.2,55.5,67.3,0.8,7.2,10.5,41.1,17.2,7.1,4.8,0.0,13.5,13.1,5.2,1.5,61803,33.0,7.5,53.6,1.4,26262,52039,27763,40.8,40.8,6.2,24.2,0.0,29.4,1828,95.1,0.0,1.5,1828,36,005,037100,63.2,0.0,1.8,19.9,1739,10.4,1558,4.02,3.5,41.1,0.0,5.5,0.0,30.9,2301,795,6.2,20.5,1.1,0.0,27.3,4322,19,2504,high,198178,0.0044
4,"Census Tract 385, Bronx County, New York",4757,1674,1028,38.9,38.6,2.80,3.75,4.0,49,0.0,17.6,23.1,7.0,90.5,0.9,61.7,67.9,0.4,13.2,10.6,46.2,15.7,3.1,7.7,0.0,25.1,17.1,3.1,0.8,36603,18.9,9.7,60.5,0.4,18641,24963,29083,21.8,21.8,16.8,44.6,55.0,59.5,1829,91.5,52.7,4.0,1829,36,005,038500,72.9,0.0,4.4,12.7,1674,1.6,1648,2.19,2.9,26.7,26.9,0.0,0.0,0.0,2750,1034,12.4,12.2,0.2,0.0,8.3,4757,18,3443,high,189195,0.0038

In [106]:
dc_NYCAll_withCrime.head()

,NAME,DP05_0001E-T Popo,DP02_0001E-T HHs,DP02_0002E-T Fam HHs,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0015E-Avg HH Size,DP02_0016E-Avg Fam Size,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0065E-HH-MeanEarnings,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0092E-Median Earning Workers,DP03_0093E-Median Earnings Male FT Workers,DP03_0094E-Median Earnings Female FT Workers,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0001E-T H U,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0006E-T HU,State,County,Tract,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0045PE-%Occup HU,DP04_0046PE-%Owner Occup HU,DP04_0048E-Owner Ave Household size,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP04_0101E-Med Onwer Monthly Mortgage,DP04_0134E-Median Gross Rent,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,DP05_0070PE-%H&L race,AreaLand,crimeStats,crime,ALAND,Popo_Density_Per_Hector
0,"Census Tract 429.02, Bronx County, New York",4205,1599,967,25.1,39.5,2.56,3.39,4.5,92,23.0,10.9,16.2,6.2,84.9,1.2,51.0,65.9,3.7,18.1,23.4,28.0,13.6,1.8,15.2,0.0,11.8,14.1,7.5,0.0,52789,18.7,18.9,44.7,0.0,21505,40850,28938,37.7,37.7,11.9,37.6,37.0,71.6,1647,97.1,0.0,2.1,1647,36,005,042902,77.2,3.2,4.4,5.5,1599,9.8,1442,2.05,5.7,23.0,43.3,0.0,0.0,14.0,3629,1354,9.9,13.7,2.3,0.2,14.0,4205,9,901,low,94576,0.0021
1,"Census Tract 330, Bronx County, New York",5885,2129,1433,12.3,32.7,2.76,3.43,4.6,104,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,52566,18.0,5.1,35.5,0.0,27189,36468,31750,38.0,38.0,17.3,18.1,11.5,76.0,2238,95.1,0.0,3.5,2238,36,005,033000,66.9,0.9,1.2,10.0,2129,4.9,2024,3.32,1.6,46.6,18.1,0.0,0.0,5.7,-666666666,1206,6.9,15.8,0.0,0.0,50.0,5885,20,2490,high,206129,0.0034
2,"Census Tract 358, Bronx County, New York",8054,2443,1885,23.1,22.8,3.27,3.66,6.6,84,0.0,5.7,6.0,11.0,89.6,0.4,53.1,30.0,0.0,11.1,38.7,24.6,11.7,6.9,5.6,0.0,2.0,7.6,16.2,7.1,90805,35.2,0.0,15.5,8.4,32354,43970,41750,70.1,70.1,4.3,5.5,9.8,0.0,2551,95.8,1.6,3.5,2551,36,005,035800,3.1,0.0,0.9,2.9,2443,65.9,834,3.34,1.9,30.7,1.1,0.0,0.0,18.6,2817,1431,5.4,19.0,0.0,0.0,10.4,8054,65,1667,low,651471,0.0081
3,"Census Tract 371, Bronx County, New York",4322,1739,888,20.2,48.9,2.46,3.68,3.8,54,4.8,0.0,19.6,5.1,94.0,1.2,55.5,67.3,0.8,7.2,10.5,41.1,17.2,7.1,4.8,0.0,13.5,13.1,5.2,1.5,61803,33.0,7.5,53.6,1.4,26262,52039,27763,40.8,40.8,6.2,24.2,0.0,29.4,1828,95.1,0.0,1.5,1828,36,005,037100,63.2,0.0,1.8,19.9,1739,10.4,1558,4.02,3.5,41.1,0.0,5.5,0.0,30.9,2301,795,6.2,20.5,1.1,0.0,27.3,4322,19,2504,high,198178,0.0044
4,"Census Tract 385, Bronx County, New York",4757,1674,1028,38.9,38.6,2.80,3.75,4.0,49,0.0,17.6,23.1,7.0,90.5,0.9,61.7,67.9,0.4,13.2,10.6,46.2,15.7,3.1,7.7,0.0,25.1,17.1,3.1,0.8,36603,18.9,9.7,60.5,0.4,18641,24963,29083,21.8,21.8,16.8,44.6,55.0,59.5,1829,91.5,52.7,4.0,1829,36,005,038500,72.9,0.0,4.4,12.7,1674,1.6,1648,2.19,2.9,26.7,26.9,0.0,0.0,0.0,2750,1034,12.4,12.2,0.2,0.0,8.3,4757,18,3443,high,189195,0.0038

In [107]:
## converting all data columns to numeric
for col in  dc_NYCAll_withCrime.filter(like='DP').columns:
    dc_NYCAll_withCrime[col] = pd.to_numeric(dc_NYCAll_withCrime[col], errors='coerce')

#dc_NYCAll_withCrime[cols] = dc_NYCAll_withCrime[cols].apply(pd.to_numeric, errors='coerce', axis=1)

<ipython-input-107-0848ce09c024>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dc_NYCAll_withCrime[col] = pd.to_numeric(dc_NYCAll_withCrime[col], errors='coerce')

In [108]:
dc_NYCAll_withCrime.describe()

,DP05_0001E-T Popo,DP02_0001E-T HHs,DP02_0002E-T Fam HHs,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0015E-Avg HH Size,DP02_0016E-Avg Fam Size,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0065E-HH-MeanEarnings,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0092E-Median Earning Workers,DP03_0093E-Median Earnings Male FT Workers,DP03_0094E-Median Earnings Female FT Workers,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0001E-T H U,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0006E-T HU,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0045PE-%Occup HU,DP04_0046PE-%Owner Occup HU,DP04_0048E-Owner Ave Household size,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP04_0101E-Med Onwer Monthly Mortgage,DP04_0134E-Median Gross Rent,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,DP05_0070PE-%H&L race,AreaLand,crimeStats,ALAND,Popo_Density_Per_Hector
count,2140.000000,2140.000000,2140.000000,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2140.000000,2140.000000,2140.000000,2140.000000,2140.000000,2140.000000,2140.000000,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2140.000000,2.140000e+03,2.140000e+03,2.140000e+03,2140.000000,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2140.000000,2.140000e+03,2140.000000,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2.140000e+03,2140.000000,2140.000000,2140.000000,2140.000000,2140.000000,2140.000000,2140.000000,2140.000000,2.140000e+03,2140.000000
mean,3983.670093,1487.314486,892.153738,-2.180667e+06,-2.180650e+06,-2.492209e+06,-2.492208e+06,-2.180678e+06,-2.492190e+06,-6.355140e+07,-6.355139e+07,8.981822,6.626402,90.260841,1.030748,58.970981,47.569907,4.406542,-1.557625e+06,-1.557594e+06,-1.557609e+06,-1.557623e+06,-1.557624e+06,-1.557620e+06,-1.557632e+06,-2.180677e+06,-2.180676e+06,-2.180674e+06,-2.180676e+06,-5.978693e+06,-2.180659e+06,-2.180681e+06,-2.180666e+06,-2.492200e+06,-3.696914e+06,-8.041421e+06,-1.022976e+07,-6.229948e+05,-6.229948e+05,-6.230445e+05,-2.492197e+06,-1.931463e+07,-2.461056e+07,1636.927103,-2.180594e+06,-1.682243e+07,-3.115261e+06,1636.927103,-2.180649e+06,-2.180685e+06,-2.180681e+06,-2.180679e+06,1487.314486,-2.180648e+06,997.652336,-2.087227e+07,-2.180682e+06,-2.180658e+06,-1.775701e+07,-1.775701e+07,-1.775701e+07,-1.775697e+07,-7.632155e+07,-9.032782e+06,6.414579,17.532570,0.742150,0.754813,44.887523,3983.670093,34.038785,2431.789720,3.453997e+05,0.141873
std,2200.391752,991.694852,502.313606,3.807509e+07,3.807509e+07,4.069444e+07,4.069444e+07,3.807509e+07,4.069444e+07,1.958232e+08,1.958232e+08,6.140322,3.240043,6.952715,1.336921,14.899679,22.395930,5.915817,3.219441e+07,3.219441e+07,3.219441e+07,3.219441e+07,3.219441e+07,3.219441e+07,3.219441e+07,3.807509e+07,3.807509e+07,3.807509e+07,3.807509e+07,7.146216e+07,3.807509e+07,3.807509e+07,3.807509e+07,4.069444e+07,4.979664e+07,7.305906e+07,8.217112e+07,2.037583e+07,2.037583e+07,2.037583e+07,4.069444e+07,1.118446e+08,1.257329e+08,1114.571527,3.807509e+07,1.045804e+08,4.547642e+07,1114.571527,3.807509e+07,3.807509e+07,3.807509e+07,3.807509e+07,991.694852,3.807509e+07,854.625878,1.161271e+08,3.807509e+07,3.807509e+07,1.073689e+08,1.073689e+08,1.073689e+08,1.073689e+08,2.123176e+08,7.709755e+07,3.083007,7.790261,1.367829,1.239501,29.711417,2200.391752,61.773689,4023.429329,6.177147e+05,2.930504
min,3.000000,0.000000,0.000000,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-1.000000e+09,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,0.000000,-6.666667e+08,-6.666667e+08,-6.666667e+08,0.000000,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,0.000000,-6.666667e+08,0.000000,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,-6.666667e+08,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,3.000000,1.000000,3.866000e+04,0.000900
25%,2422.250000,820.000000,543.750000,9.400000e+00,2.380000e+01,2.380000e+00,3.110000e+00,3.500000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.400000,4.300000,87.700000,0.000000,48.700000,28.200000,0.400000,4.000000e+00,2.517500e+01,1.540000e+01,6.800000e+00,5.000000e+00,8.000000e+00,0.000000e+00,3.700000e+00,5.500000e+00,7.900000e+00,2.400000e+00,6.710700e+04,2.000000e+01,1.300000e+00,7.200000e+00,2.400000e+00,2.836100e+04,4.003300e+04,3.739825e+04,4.420000e+01,4.420000e+01,4.700000e+00,5.500000e+00,0.000000e+00,0.000000e+00,888.750000,8.890000e+01,0.000000e+00,0.000000e+00,888.750000,3.200000e+00,0.000000e+00,1.200000e+00,1.700000e+00,820.000000,1.610000e+01,380.000000,2.420000e+00,1.300000e+00,2.237500e+01,0.000000e+00,0.000000e+00,0.000000e+00,2.110000e+01,2.174750e+03,1.261000e+03,4.400000,12.500000,0.000000,0.000000,16.400000,2422.250000,15.000000,411.750000,1.564098e+05,0.003600
50%,3591.500000,1271.000000,790.000000,1.570000e+01,3.290000e+01,2.780000e+00,3.400000e+00,5.550000e+00,8.000000e+00,0.000000e+00,0.000000e+00,8.000000,6.400000,91.800000,0.600000,58.600000,47.300000,2.100000,6.200000e+00,3.560000e+01,2.370000e+01,9.200000e+00,7.300000e+00,1.090000e+01,0.000000e+00,6.600000e+00,8.600000e+00,1.110000e+01,5.700000e+00,8.504600e+04,2.630000e+01,3.100000e+00,1.480000e+01,6.500000e+00,3.658600e+04,5.036450e+04,4.641500e+04,5.860000e+01,5.860000e+01,7.500000e+00,1.170000e+01,0.000000e+00,2.735000e+01,1406.500000,9.245000e+01,0.000000e+00,2.500000e+00,1406.500000,2.755000e+01,0.000000e+00,3.200000e+00,4.600000e+00,1271.000000,3.345000e+01,762.000000,2.980000e+00,2.950000e+00,2.690000e+01,0.000000e+00,0.000000e+00,0.000000e+00,3.790000e+01,2.656000e+03,1.431000e+03,6.100000,16.400000,0.300000,0.200000,43.050000,3591.500000,18.000000,1053.000000,1.841745e+05,0.005800
75%,5028.250000,1856.750000,1130.000000,2.610000e+01,4.572500e+01,3.170000e+00,3.710000e+00,9.100000e+00,3.400000e+01,2.500000e+00,1.570000e+01,12.500000,8.600000,94.600000,1.400000,70.600000,66.000000,6.700000,9.100000e+00,4.860000e+01,3.120000e+01,1.200000e+01,1.042500e+01,1.520000e+01,0.000000e+00,1.110000e+01,1.260000e+01,1.430000e+01,1.100000e+01,1.076028e+05,3.262500e+01,6.100000e+00,2.810000e+01,1.360000e+01,4.823975e+04,6.484500e+04,5.971925e+04,7.262500e+01,7.262500e+01,1.100000e+01,2.132500e+01,2.540000e+01,4.872500e+01,2024.000000,9.520000e+01,2.400000e+00,5.300000e+00,2024.000000,6.830000e+01,0.000000e+00,6.600000e+00,8.900000e+00,1856.750000,5.675000e+01,1374.250000,3.480000e+00,5.000000e+00,3.200000e+01,1.500000e+00,1.900000e+00,2.025000e+00,5.490000e+01,3.067000e+03,1.666000e+03,8.100000,21.400000,1.000000,1.100000,72.500000,5028.250000,28.000000,2742.250000,2.854888e+05,0.010100
max,28272.000000,12827.000000,6960.000000,1.000000e+02,1.000000e+02,6.540000e+00,7.200000e+00,5.120000e+01,1.000000e+03,1.000000e+02,1.000000e+02,60.000000,26.700000,100.000000,14.900000,100.000000,100.000000,62.000000,3.420000e+01,1.000000e+02,6.420000e+01,1.000000e+02,4.740000e+01,5.000000e+01,6.100000e+00,5.010000e+01,1.000000e+02,4.690000e+01,8.840000e+01,4.342320e+05,1.000000e+02,4.140000e+01,1.000000e+02,7.880000e+01,1.626500e+05,2.500010e+05,2.150960e+05,1.000000e+02,1.000000e+02,5.320000e+01,1.000000e+02,1.000000e+02,1.000000e+02,13028.000000,1.000000e+02,5.270000e+01,4.240000e+01,13028.000000,1.000000e+02,4.410000e+01,5.000000e+01,7.250000e+01,12827.000000,1.000000e+02,8145.000000,8.260000e+00,2.730000e+01,1.000000e+02,1.000000e+02,1.000000e+02,1.000000e+02,1.000000e+02,4.001000e+03,3.501000e+03,33.300000,100.000000,24.200000,14.900000,100.000000,28272.000000,963.000000,66178.000000,9.631178e+06,99.666700

In [44]:
dc_NYCAll_withCrime.isna().sum()

NAME                                            0
DP05_0001E-T Popo                               0
DP02_0001E-T HHs                                0
DP02_0002E-T Fam HHs                            0
DP02_0008PE-%F-led HHs No H                     0
DP02_0010PE-% Non-Fam HHs                       0
DP02_0015E-Avg HH Size                          0
DP02_0016E-Avg Fam Size                         0
DP02_0022PE-%Non Rel in Hs                      0
DP02_0038E-per1000-F-U-RecentPreg               0
DP02_0046PE-%GPwParent&Gc1-2yrs                 0
DP02_0048PE--%GPwParent&Gc>5yrs                 0
DP02_0060PE-%NoSchDiploma                       0
DP02_0063PE-%AssDeg                             0
DP02_0079PE-% SameHouse_1YrAgo                  0
DP02_0085PE-%LivAbroad1YrAgo                    0
DP02_0088PE-%BornUS                             0
DP02_0112PE-HomeLangNotEng                      0
DP02_0134PE-%IrishAnc                           0
DP03_0009PE-%Unemploy                           0
DP03_0027PE-%WorkingMgt,Bus,Sc,Arts             0
DP03_0028PE%WorkingService                      0
DP03_0037PE-Retail                              0
DP03_0040PE-%Fin&Ins                            0
DP03_0041PE-%ProfSc,Mgt,Admin                   0
DP03_0050PE-%UnpaidFamilyWk                     0
DP03_0052PE-Inc<10k                             0
DP03_0054PE-Inc15-24k                           0
DP03_0058PE-Inc75-99k                           0
DP03_0061PE-Inc200k>                            0
DP03_0065E-HH-MeanEarnings                      0
DP03_0066PE-%HHsWithSocSec                      0
DP03_0072PE-%HH Inc with Cash public Ass        0
DP03_0074PE-%HH Inc with Food Stamps SNAP       0
DP03_0085PE-%Families Inc>200k                  0
DP03_0092E-Median Earning Workers               0
DP03_0093E-Median Earnings Male FT Workers      0
DP03_0094E-Median Earnings Female FT Workers    0
DP03_0097PE-%PHI-Priv                           0
DP03_0098PE-%PHI-Pub                            0
DP03_0099PE-No PHI                              0
DP03_0119PE-% Fam <Pov                          0
DP03_0121PE-%Fam with child U18&U5 <pov         0
DP03_0126PE-%F-Led Families with u18 <pov       0
DP04_0001E-T H U                                0
DP04_0002PE-%Occ H U                            0
DP04_0004E-%Ow Vac Rate                         0
DP04_0005E-%Rn Vac Rate                         0
DP04_0006E-T HU                                 0
State                                           0
County                                          0
Tract                                           0
DP04_0013PE-%20+HU                              0
DP04_0017PE-%Built2014+                         0
DP04_0029PE-%2rooms_only_HU                     0
DP04_0039PE-Zero bedrooms                       0
DP04_0045PE-%Occup HU                           0
DP04_0046PE-%Owner Occup HU                     0
DP04_0048E-Owner Ave Household size             0
DP04_0049E-Renter Ave Household size            0
DP04_0051PE-%moved since 2017+                  0
DP04_0054PE-%moved 2000 to 2009                 0
DP04_0082PE-%Value 50-99k                       0
DP04_0083PE-%Value 100-149k                     0
DP04_0084PE-%Value 150-199k                     0
DP04_0087PE-%Value 500k-1m                      0
DP04_0101E-Med Onwer Monthly Mortgage           0
DP04_0134E-Median Gross Rent                    0
DP05_0005PE-%under 5 yrs                        0
DP05_0023PE-%62 yrs+                            0
DP05_0058PE-% w & B or AM                       0
DP05_0061PE-%White & Asian                      0
DP05_0064PE-%White with others                  0
DP05_0070PE-%H&L race                           0
AreaLand                                        0
crimeStats                                      0
crime                                           0
ALAND                                           0
Popo_Density_Per_Hector                         0
dtype: int64

In [109]:
dc_NYCAll_withCrime.loc[dc_NYCAll_withCrime.crimeStats == 0, 'crimeStats'].count()

0

In [110]:
dc_NYCAll_withCrime.groupby('crime').count()

,NAME,DP05_0001E-T Popo,DP02_0001E-T HHs,DP02_0002E-T Fam HHs,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0015E-Avg HH Size,DP02_0016E-Avg Fam Size,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0065E-HH-MeanEarnings,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0092E-Median Earning Workers,DP03_0093E-Median Earnings Male FT Workers,DP03_0094E-Median Earnings Female FT Workers,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0001E-T H U,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0006E-T HU,State,County,Tract,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0045PE-%Occup HU,DP04_0046PE-%Owner Occup HU,DP04_0048E-Owner Ave Household size,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP04_0101E-Med Onwer Monthly Mortgage,DP04_0134E-Median Gross Rent,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,DP05_0070PE-%H&L race,AreaLand,crimeStats,ALAND,Popo_Density_Per_Hector
crime,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
high,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605,605
low,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535,1535

In [111]:
## save file to local drive
dc_NYCAll_withCrime.to_csv("NYC_CSV__Feb21th_before.csv") ## 516kB

In [120]:
NYClist_of_counties = ["005", "047", "059", "061", "081", "085", "119"]
census_tract_NYC['COUNTYFP'] = census_tract_NYC['COUNTYFP'].apply(lambda x: '{0:0>3}'.format(x)).astype(str)
census_tract_NYC = census_tract_NYC[census_tract_NYC['COUNTYFP'].isin(NYClist_of_counties)]
census_tract_NYC

     STATEFP COUNTYFP TRACTCE              AFFGEOID        GEOID    NAME LSAD   ALAND  AWATER
3         36      081  046200  1400000US36081046200  36081046200  462.00   CT  249611       0
4         36      081  048100  1400000US36081048100  36081048100  481.00   CT  139052       0
5         36      081  049600  1400000US36081049600  36081049600  496.00   CT  273116       0
11        36      081  050202  1400000US36081050202  36081050202  502.02   CT  152854       0
20        36      005  040400  1400000US36005040400  36005040400  404.00   CT  215289       0
...      ...      ...     ...                   ...          ...     ...  ...     ...     ...
4897      36      005  040100  1400000US36005040100  36005040100  401.00   CT  170429       0
4898      36      005  041400  1400000US36005041400  36005041400  414.00   CT  522982       0
4899      36      081  010400  1400000US36081010400  36081010400  104.00   CT  186476       0
4900      36      061  019000  1400000US36061019000  36061019000  190.00   CT  103802       0
4901      36      047  059100  1400000US36047059100  36047059100  591.00   CT  192105       0

[2668 rows x 9 columns]

In [122]:
## save NYC city tract file to local drive
##dc_NYCAll_withCrimeNoNAs.to_csv("dc_NYCAll_withCrimeNov30th.csv")
census_tract_NYC.to_csv("census_tracts_NYCFeb21th.csv")