In [19]:
## Step 2 joins data from various city and then cleans up the data, turning all data to numeric

import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 100)
url_NYC = 'https://raw.githubusercontent.com/maireadmanifold/files/main/NYC_CSV__Feb21th_before.csv'
df_ML_NYC = pd.read_csv(url_NYC, error_bad_lines=False, index_col=0)
url_Baltimore = 'https://raw.githubusercontent.com/maireadmanifold/files/main/Baltimore_CSV__Feb8th_before.csv'
df_ML_Baltimore = pd.read_csv(url_Baltimore, error_bad_lines=False, index_col=0)
url_Chicago = 'https://raw.githubusercontent.com/maireadmanifold/files/main/Chicago_CSV__Feb12th_before.csv'
df_ML_Chicago = pd.read_csv(url_Chicago, error_bad_lines=False, index_col=0)
url_LA = 'https://raw.githubusercontent.com/maireadmanifold/files/main/LA_CSV__Feb9th_before.csv'
df_ML_LA = pd.read_csv(url_LA, error_bad_lines=False, index_col=0)
url_SF = 'https://raw.githubusercontent.com/maireadmanifold/files/main/SF_CSV__Feb8th_before.csv'
df_ML_SF = pd.read_csv(url_SF, error_bad_lines=False, index_col=0)
url_Dallas = 'https://raw.githubusercontent.com/maireadmanifold/files/main/Dallas_CSV_Feb8th_before.csv'
df_ML_Dallas = pd.read_csv(url_Dallas, error_bad_lines=False, index_col=0)

In [20]:
## Note that the % S & L is a number rather than a %

In [21]:
df_ML_NYC[1:3]

,NAME,DP05_0001E-T Popo,DP02_0001E-T HHs,DP02_0002E-T Fam HHs,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0015E-Avg HH Size,DP02_0016E-Avg Fam Size,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0065E-HH-MeanEarnings,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0092E-Median Earning Workers,DP03_0093E-Median Earnings Male FT Workers,DP03_0094E-Median Earnings Female FT Workers,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0001E-T H U,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0006E-T HU,State,County,Tract,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0045PE-%Occup HU,DP04_0046PE-%Owner Occup HU,DP04_0048E-Owner Ave Household size,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP04_0101E-Med Onwer Monthly Mortgage,DP04_0134E-Median Gross Rent,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,DP05_0070PE-%H&L race,AreaLand,crimeStats,crime,ALAND,Popo_Density_Per_Hector
1,"Census Tract 330, Bronx County, New York",5885,2129,1433,12.3,32.7,2.76,3.43,4.6,104,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,52566,18.0,5.1,35.5,0.0,27189,36468,31750,38.0,38.0,17.3,18.1,11.5,76.0,2238,95.1,0.0,3.5,2238,36,5,33000,66.9,0.9,1.2,10.0,2129,4.9,2024,3.32,1.6,46.6,18.1,0.0,0.0,5.7,-666666666,1206,6.9,15.8,0.0,0.0,50.0,5885,20,2490,high,206129,0.0034
2,"Census Tract 358, Bronx County, New York",8054,2443,1885,23.1,22.8,3.27,3.66,6.6,84,0.0,5.7,6.0,11.0,89.6,0.4,53.1,30.0,0.0,11.1,38.7,24.6,11.7,6.9,5.6,0.0,2.0,7.6,16.2,7.1,90805,35.2,0.0,15.5,8.4,32354,43970,41750,70.1,70.1,4.3,5.5,9.8,0.0,2551,95.8,1.6,3.5,2551,36,5,35800,3.1,0.0,0.9,2.9,2443,65.9,834,3.34,1.9,30.7,1.1,0.0,0.0,18.6,2817,1431,5.4,19.0,0.0,0.0,10.4,8054,65,1667,low,651471,0.0081

In [22]:
df_ML_Baltimore[1:3]

,NAME,DP05_0001E-T Popo,DP02_0001E-T HHs,DP02_0002E-T Fam HHs,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0015E-Avg HH Size,DP02_0016E-Avg Fam Size,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0065E-HH-MeanEarnings,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0092E-Median Earning Workers,DP03_0093E-Median Earnings Male FT Workers,DP03_0094E-Median Earnings Female FT Workers,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0001E-T H U,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0006E-T HU,State,County,Tract,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0045PE-%Occup HU,DP04_0046PE-%Owner Occup HU,DP04_0048E-Owner Ave Household size,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP04_0101E-Med Onwer Monthly Mortgage,DP04_0134E-Median Gross Rent,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,DP05_0070PE-%H&L race,AreaLand,crimeStats,crime,ALAND,Popo_Density_Per_Hector
1,"Census Tract 7501.01, Anne Arundel County, Mar...",4264,1556,932,18.4,40.1,2.72,3.50,8.3,18,0.0,21.0,8.1,6.9,92.3,1.4,90.3,10.7,6.7,6.9,26.3,25.8,11.3,3.1,14.8,0.0,6.9,9.6,15.6,2.0,70388,32.6,3.1,16.7,1.1,34909,53018,35139,60.2,60.2,6.2,12.3,0.0,25.4,1635,95.2,0.6,5.3,1635,24,3,750101,0.0,0.0,0.4,1.4,1556,72.3,431,2.75,1.3,38.8,13.1,11.1,18.6,0.8,1416,1115,7.0,13.7,4.8,0.9,72.3,4264,134,26,low,1345542,0.0314
2,"Census Tract 7502.01, Anne Arundel County, Mar...",3436,1215,893,20.0,26.5,2.73,3.09,6.9,146,10.8,10.8,12.3,5.6,80.4,0.0,89.0,14.6,5.8,7.7,28.8,26.5,10.3,3.7,15.5,0.0,7.8,9.2,14.9,3.5,70568,37.5,3.0,28.5,2.5,32181,52018,34869,48.9,48.9,16.2,10.6,0.0,0.0,1269,95.7,0.0,7.0,1269,24,3,750201,6.4,0.6,2.6,0.0,1215,76.0,292,2.86,5.6,20.0,2.0,7.6,13.2,0.0,1647,927,9.2,23.7,0.0,0.0,55.3,3436,328,2,low,3287938,0.0955

In [23]:
df_ML_Chicago[1:3]

,NAME,DP05_0001E-T Popo,DP02_0001E-T HHs,DP02_0002E-T Fam HHs,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0015E-Avg HH Size,DP02_0016E-Avg Fam Size,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0065E-HH-MeanEarnings,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0092E-Median Earning Workers,DP03_0093E-Median Earnings Male FT Workers,DP03_0094E-Median Earnings Female FT Workers,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0001E-T H U,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0006E-T HU,State,County,Tract,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0045PE-%Occup HU,DP04_0046PE-%Owner Occup HU,DP04_0048E-Owner Ave Household size,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP04_0101E-Med Onwer Monthly Mortgage,DP04_0134E-Median Gross Rent,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,DP05_0070PE-%H&L race,AreaLand,crimeStats,crime,ALAND,Popo_Density_Per_Hector
1,"Census Tract 4205, Cook County, Illinois",1659,799,369,23.8,53.8,2.08,3.15,4.0,0,0.0,23.5,10.1,14.4,92.9,0.0,93.5,14.4,0.0,25.8,41.1,30.8,9.0,3.3,22.9,1.0,16.8,15.4,15.4,0.0,45341,41.3,6.1,30.4,0.0,29367,49018,29495,45.0,45.0,7.5,11.4,25.8,25.3,1136,70.3,14.7,12.5,1136,17,31,420500,37.1,4.5,2.2,2.5,799,18.9,648,1.80,1.3,24.0,2.6,21.2,39.1,0.0,1205,939,5.2,24.2,1.0,0.0,1.0,1659,24,245,high,245980,0.0145
2,"Census Tract 4304, Cook County, Illinois",2756,1087,537,39.6,50.6,2.43,3.81,1.9,70,10.5,0.0,7.7,7.9,80.8,0.0,96.9,2.1,2.0,16.7,29.5,30.8,5.2,7.2,7.9,0.0,27.0,8.4,7.3,0.0,42317,24.0,3.3,39.5,0.0,30331,34407,31659,40.7,40.7,5.2,26.1,18.2,28.3,1430,76.0,20.4,15.9,1430,17,31,430400,8.4,0.0,2.4,7.8,1087,27.4,789,2.55,14.4,15.5,36.9,18.5,17.4,0.0,1511,946,5.9,13.7,0.0,0.0,4.0,2756,54,376,high,548003,0.0196

In [24]:
df_ML_LA[1:3]

,NAME,DP05_0001E-T Popo,DP02_0001E-T HHs,DP02_0002E-T Fam HHs,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0015E-Avg HH Size,DP02_0016E-Avg Fam Size,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0065E-HH-MeanEarnings,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0092E-Median Earning Workers,DP03_0093E-Median Earnings Male FT Workers,DP03_0094E-Median Earnings Female FT Workers,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0001E-T H U,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0006E-T HU,State,County,Tract,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0045PE-%Occup HU,DP04_0046PE-%Owner Occup HU,DP04_0048E-Owner Ave Household size,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP04_0101E-Med Onwer Monthly Mortgage,DP04_0134E-Median Gross Rent,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,DP05_0070PE-%H&L race,AreaLand,crimeStats,crime,ALAND,Popo_Density_Per_Hector
1,"Census Tract 5501, Los Angeles County, California",7441,1886,1587,12.6,15.9,3.95,4.27,4.9,46,2.0,3.3,10.1,7.3,97.5,0.2,64.1,74.0,0.8,4.6,28.7,20.0,12.4,5.8,4.2,0.0,3.8,5.4,17.0,5.6,84915,23.8,2.7,5.5,4.2,31603,42163,33976,73.6,73.6,3.0,7.5,5.4,6.3,1954,96.5,3.7,0.0,1954,6,37,550100,3.5,0.0,0.4,2.1,1886,81.8,344,3.89,0.5,29.5,0.0,0.0,0.0,9.4,1914,1253,6.6,14.9,0.0,0.9,49.0,7441,164,1,low,1648945,0.0220
2,"Census Tract 6031.02, Los Angeles County, Cali...",3742,1334,828,11.1,37.9,2.79,3.59,6.6,54,0.0,22.2,9.1,9.3,94.6,0.0,59.7,62.9,0.8,6.2,33.7,11.5,10.6,4.2,21.4,0.0,6.3,10.6,13.8,2.7,71045,39.3,4.2,9.2,4.3,36120,46522,36771,54.2,54.2,6.4,15.6,0.0,26.5,1452,91.9,0.0,6.0,1452,6,37,603102,14.2,1.2,2.1,6.1,1334,33.6,886,3.07,2.7,40.6,0.0,0.0,3.8,37.1,2337,1262,5.4,22.5,0.0,1.8,30.7,3742,74,45,low,745751,0.0198

In [25]:
df_ML_SF [1:3]

,NAME,DP05_0001E-T Popo,DP02_0001E-T HHs,DP02_0002E-T Fam HHs,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0015E-Avg HH Size,DP02_0016E-Avg Fam Size,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0065E-HH-MeanEarnings,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0092E-Median Earning Workers,DP03_0093E-Median Earnings Male FT Workers,DP03_0094E-Median Earnings Female FT Workers,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0001E-T H U,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0006E-T HU,State,County,Tract,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0045PE-%Occup HU,DP04_0046PE-%Owner Occup HU,DP04_0048E-Owner Ave Household size,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP04_0101E-Med Onwer Monthly Mortgage,DP04_0134E-Median Gross Rent,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,DP05_0070PE-%H&L race,AreaLand,crimeStats,crime,ALAND,Popo_Density_Per_Hector
1,"Census Tract 102, San Francisco County, Califo...",4299,2541,813,2.8,68.0,1.69,2.38,14.7,0,-666666666.0,-666666666.0,1.5,2.4,80.7,3.0,76.5,8.8,10.3,0.7,71.1,5.5,10.9,17.1,36.3,0.0,2.3,3.0,4.7,29.9,202319,24.7,1.1,1.1,39.0,93125,126733,84512,87.2,87.2,3.5,3.7,0.0,0.0,3015,84.3,0.0,0.8,3015,6,75,10200,35.9,0.0,13.1,10.8,2541,35.8,1632,1.71,5.5,28.0,1.4,0.0,0.0,38.3,4001,2449,2.0,27.1,1.1,2.0,83.7,4299,51,15427,high,515958,0.0119
2,"Census Tract 108, San Francisco County, Califo...",4860,2466,910,1.4,63.1,1.97,2.79,15.7,0,0.0,12.2,3.1,4.2,85.5,2.3,66.0,40.4,10.8,4.5,57.8,10.3,8.4,10.7,31.2,0.7,4.0,5.2,10.9,19.5,159806,29.0,0.5,4.7,27.8,76771,101324,100667,73.5,73.5,1.9,10.7,0.0,100.0,2754,89.5,0.0,0.8,2754,6,75,10800,12.8,0.0,10.6,12.6,2466,24.9,1852,2.05,9.6,16.0,0.0,0.0,0.0,31.4,3847,1779,4.8,25.6,0.0,1.8,54.9,4860,22,3953,low,226078,0.0045

In [26]:
df_ML_Dallas[1:3]

,NAME,DP05_0001E-T Popo,DP02_0001E-T HHs,DP02_0002E-T Fam HHs,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0015E-Avg HH Size,DP02_0016E-Avg Fam Size,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0065E-HH-MeanEarnings,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0092E-Median Earning Workers,DP03_0093E-Median Earnings Male FT Workers,DP03_0094E-Median Earnings Female FT Workers,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0001E-T H U,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0006E-T HU,State,County,Tract,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0045PE-%Occup HU,DP04_0046PE-%Owner Occup HU,DP04_0048E-Owner Ave Household size,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP04_0101E-Med Onwer Monthly Mortgage,DP04_0134E-Median Gross Rent,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,DP05_0070PE-%H&L race,AreaLand,crimeStats,crime,Popo_Density_Per_Hector
1,"Census Tract 178.13, Dallas County, Texas",6896,2441,1733,23.9,29.0,2.83,3.25,8.1,160,0.0,0.0,12.4,6.8,71.5,1.2,77.8,38.2,3.3,5.4,26.1,12.7,16.7,7.3,13.3,0.0,1.9,7.7,12.0,1.4,59139,10.7,1.2,16.8,1.9,31881,39051,34004,53.0,53.0,26.5,7.1,12.8,6.8,2753,88.7,12.7,9.0,2753,48,113,17813,16.7,0.4,2.7,4.6,2441,19.5,1965,3.06,11.1,9.6,25.0,53.4,19.3,0.0,1272,1056,9.1,7.2,1.2,1.4,52.4,6896,281,1,low,0.04
2,"Census Tract 184.01, Dallas County, Texas",5025,1498,1094,16.4,27.0,3.35,4.09,2.8,133,1.9,16.8,22.3,5.2,85.1,0.3,71.7,55.6,3.3,3.6,22.0,11.9,9.8,6.3,10.2,0.0,2.5,12.5,14.4,5.8,70365,25.8,0.7,18.6,5.3,24835,40911,26406,46.4,46.4,30.4,21.9,78.6,64.9,1566,95.7,2.9,6.5,1566,48,113,18401,3.2,0.0,3.2,0.0,1498,61.9,571,3.11,3.7,21.9,17.6,37.5,33.7,0.8,1339,917,8.1,11.9,2.9,0.2,73.5,5025,245,2,low,0.05

In [27]:
data_frames = [df_ML_NYC, df_ML_Baltimore, df_ML_Chicago, df_ML_LA, df_ML_SF, df_ML_Dallas]
All_CSVs = pd.concat(data_frames)

In [28]:
## REMOVE when done with individual data files and adding in index from shape file
All_CSVs.to_csv("All_Step2_CSVsMar6th.csv")

In [29]:
## changing everything to numeric 
import numpy as np
All_CSVs_0 = All_CSVs.copy()
All_CSVs_0[
    All_CSVs_0.apply(lambda col: pd.to_numeric(col, errors='coerce')).apply(lambda x: x < 0)
] = np.NaN
print("No of rows", All_CSVs_0.shape)
All_CSVs_0.head(4)

No of rows (5287, 79)

,NAME,DP05_0001E-T Popo,DP02_0001E-T HHs,DP02_0002E-T Fam HHs,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0015E-Avg HH Size,DP02_0016E-Avg Fam Size,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0065E-HH-MeanEarnings,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0092E-Median Earning Workers,DP03_0093E-Median Earnings Male FT Workers,DP03_0094E-Median Earnings Female FT Workers,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0001E-T H U,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0006E-T HU,State,County,Tract,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0045PE-%Occup HU,DP04_0046PE-%Owner Occup HU,DP04_0048E-Owner Ave Household size,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP04_0101E-Med Onwer Monthly Mortgage,DP04_0134E-Median Gross Rent,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,DP05_0070PE-%H&L race,AreaLand,crimeStats,crime,ALAND,Popo_Density_Per_Hector
0,"Census Tract 429.02, Bronx County, New York",4205,1599,967,25.1,39.5,2.56,3.39,4.5,92.0,23.0,10.9,16.2,6.2,84.9,1.2,51.0,65.9,3.7,18.1,23.4,28.0,13.6,1.8,15.2,0.0,11.8,14.1,7.5,0.0,52789.0,18.7,18.9,44.7,0.0,21505.0,40850.0,28938.0,37.7,37.7,11.9,37.6,37.0,71.6,1647,97.1,0.0,2.1,1647,36,5,42902,77.2,3.2,4.4,5.5,1599,9.8,1442,2.05,5.7,23.0,43.3,0.0,0.0,14.0,3629.0,1354.0,9.9,13.7,2.3,0.2,14.0,4205,9,901,low,94576.0,0.0021
1,"Census Tract 330, Bronx County, New York",5885,2129,1433,12.3,32.7,2.76,3.43,4.6,104.0,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,52566.0,18.0,5.1,35.5,0.0,27189.0,36468.0,31750.0,38.0,38.0,17.3,18.1,11.5,76.0,2238,95.1,0.0,3.5,2238,36,5,33000,66.9,0.9,1.2,10.0,2129,4.9,2024,3.32,1.6,46.6,18.1,0.0,0.0,5.7,NaN,1206.0,6.9,15.8,0.0,0.0,50.0,5885,20,2490,high,206129.0,0.0034
2,"Census Tract 358, Bronx County, New York",8054,2443,1885,23.1,22.8,3.27,3.66,6.6,84.0,0.0,5.7,6.0,11.0,89.6,0.4,53.1,30.0,0.0,11.1,38.7,24.6,11.7,6.9,5.6,0.0,2.0,7.6,16.2,7.1,90805.0,35.2,0.0,15.5,8.4,32354.0,43970.0,41750.0,70.1,70.1,4.3,5.5,9.8,0.0,2551,95.8,1.6,3.5,2551,36,5,35800,3.1,0.0,0.9,2.9,2443,65.9,834,3.34,1.9,30.7,1.1,0.0,0.0,18.6,2817.0,1431.0,5.4,19.0,0.0,0.0,10.4,8054,65,1667,low,651471.0,0.0081
3,"Census Tract 371, Bronx County, New York",4322,1739,888,20.2,48.9,2.46,3.68,3.8,54.0,4.8,0.0,19.6,5.1,94.0,1.2,55.5,67.3,0.8,7.2,10.5,41.1,17.2,7.1,4.8,0.0,13.5,13.1,5.2,1.5,61803.0,33.0,7.5,53.6,1.4,26262.0,52039.0,27763.0,40.8,40.8,6.2,24.2,0.0,29.4,1828,95.1,0.0,1.5,1828,36,5,37100,63.2,0.0,1.8,19.9,1739,10.4,1558,4.02,3.5,41.1,0.0,5.5,0.0,30.9,2301.0,795.0,6.2,20.5,1.1,0.0,27.3,4322,19,2504,high,198178.0,0.0044

In [30]:
#DP03_0065E-HH-MeanEarnings
#groupedTract_count = Dallas_points_in_map.groupby(['County','Tract','AreaLand']).size().reset_index(name='crimeStats')
#CountyTract_MeanIncome = All_CSVs.groupby(['County', 'Tract']).mean().reset_index(name='MeanEarnings')
#All_CSVs['%ofTractCountyMeanEarning']
groupedStateCountyMeanEarning = All_CSVs_0.groupby(['State','County'])['DP03_0065E-HH-MeanEarnings'].mean().sort_values(ascending=False).reset_index(name="meanCountyStateEarning")
groupedStateCountyWorkersMeanEarnings = All_CSVs_0.groupby(['State','County'])['DP03_0092E-Median Earning Workers'].mean().sort_values(ascending=False).reset_index(name="meanCountyStateWorkerEarnings")
groupedStateCountyMaleMeanEarnings = All_CSVs_0.groupby(['State','County'])['DP03_0093E-Median Earnings Male FT Workers'].mean().sort_values(ascending=False).reset_index(name="meanCountyStateMaleEarnings")
groupedStateCountyFemaleMeanEarnings = All_CSVs_0.groupby(['State','County'])['DP03_0094E-Median Earnings Female FT Workers'].mean().sort_values(ascending=False).reset_index(name="meanCountyStateFemaleEarnings")
groupedStateCountyDP040101EMedMortgage = All_CSVs_0.groupby(['State','County'])['DP04_0101E-Med Onwer Monthly Mortgage'].mean().sort_values(ascending=False).reset_index(name="meanCountyStateOwnerMortgage")
groupedStateCountyDP04_0134EMedGrossRent = All_CSVs_0.groupby(['State','County'])['DP04_0134E-Median Gross Rent'].mean().sort_values(ascending=False).reset_index(name="meanCountyStateRent")
groupedStateCountyDP05_0070PEHandL_Race = All_CSVs_0.groupby(['State','County'])['DP05_0070PE-%H&L race'].mean().sort_values(ascending=False).reset_index(name="meanCountyStateHandL_Race") # Hispanic and Latino
## added in later on
groupedStateCountyDP04_0045PEAvgHousingUnits = All_CSVs_0.groupby(['State','County'])['DP04_0045PE-%Occup HU'].mean().sort_values(ascending=False).reset_index(name="meanCountyStateAvgNoHU")
groupedStateCountyDP02_0015EAvgHHSize = All_CSVs_0.groupby(['State','County'])['DP02_0015E-Avg HH Size'].mean().sort_values(ascending=False).reset_index(name="meanCountyStateAvgHHSize")
groupedStateCountyDP04_0016PEAvgFamSize = All_CSVs_0.groupby(['State','County'])['DP02_0016E-Avg Fam Size'].mean().sort_values(ascending=False).reset_index(name="meanCountyState_AvgFamSize")

In [31]:
groupedStateCountyMeanEarning[1:6]

   State  County  meanCountyStateEarning
1      6      75                150762.0
2     24       9                147692.0
3     36      59                142546.1
4     48     397                127572.6
5      6      59                124608.0

In [32]:
print("No of rows", groupedStateCountyMeanEarning.shape)

No of rows (33, 3)

In [33]:
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)
pd.set_option('display.width', 1000)

In [34]:
All_CSVs_1 = pd.merge(left = All_CSVs_0, right = groupedStateCountyMeanEarning, how = 'inner', on = ['State', 'County'])

#All_CSVs_1[All_CSVs_1['Tract']==19700]

In [35]:
All_CSVs_1['%DP03_0065E-HH-MeanEarnings'] = (All_CSVs_1['DP03_0065E-HH-MeanEarnings']/All_CSVs_1['meanCountyStateEarning']*100) #).apply(lambda x: '{pct_mean_earnings:.1%}'.format(pct_mean_earnings = x))

In [36]:
All_CSVs_2 = pd.merge(left = All_CSVs_1, right = groupedStateCountyWorkersMeanEarnings, how = 'inner', on = ['State', 'County'])

In [37]:
All_CSVs_2['%DP03_0092E-Median Earning Workers'] = (All_CSVs_2['DP03_0092E-Median Earning Workers']/All_CSVs_2['meanCountyStateWorkerEarnings']*100) #).apply(lambda x: '{pct_mean_earnings:.1%}'.format(pct_mean_earnings = x))

In [38]:
All_CSVs_3 = pd.merge(left = All_CSVs_2, right = groupedStateCountyMaleMeanEarnings, how = 'inner', on = ['State', 'County'])

In [39]:
All_CSVs_3['%DP03_0093E-Median Earnings Male FT Workers'] = (All_CSVs_3['DP03_0093E-Median Earnings Male FT Workers']/All_CSVs_3['meanCountyStateMaleEarnings']*100) #).apply(lambda x: '{pct_mean_earnings:.1%}'.format(pct_mean_earnings = x))

In [40]:
All_CSVs_4 = pd.merge(left = All_CSVs_3, right = groupedStateCountyFemaleMeanEarnings, how = 'inner', on = ['State', 'County'])

In [41]:
All_CSVs_4['%DP03_0094E-Median Earnings Female FT Workers'] = (All_CSVs_4['DP03_0094E-Median Earnings Female FT Workers']/All_CSVs_4['meanCountyStateFemaleEarnings']*100) #).apply(lambda x: '{pct_mean_earnings:.1%}'.format(pct_mean_earnings = x))

In [42]:
All_CSVs_5 = pd.merge(left = All_CSVs_4, right = groupedStateCountyDP040101EMedMortgage, how = 'inner', on = ['State', 'County'])

In [43]:
All_CSVs_5['%DP04_0101E-Med Onwer Monthly Mortgage'] = (All_CSVs_5['DP04_0101E-Med Onwer Monthly Mortgage']/All_CSVs_5['meanCountyStateOwnerMortgage']*100) #.apply(lambda x: '{pct_mean_earnings:.1%}'.format(pct_mean_earnings = x))

In [44]:
All_CSVs_6 = pd.merge(left = All_CSVs_5, right = groupedStateCountyDP04_0134EMedGrossRent, how = 'inner', on = ['State', 'County'])

In [45]:
All_CSVs_6['%DP04_0134E-Median Gross Rent'] = (All_CSVs_6['DP04_0134E-Median Gross Rent']/All_CSVs_6['meanCountyStateRent']*100) #).apply(lambda x: '{pct_mean_earnings:.1%}'.format(pct_mean_earnings = x))

In [46]:
All_CSVs_7 = pd.merge(left = All_CSVs_6, right = groupedStateCountyDP05_0070PEHandL_Race, how = 'inner', on = ['State', 'County'])

In [47]:
All_CSVs_7['%DP05_0070PE-%H&L race'] = (All_CSVs_7['DP05_0070PE-%H&L race']/All_CSVs_7['meanCountyStateHandL_Race']*100) #.apply(lambda x: '{pct_mean_earnings:.1%}'.format(pct_mean_earnings = x))

In [48]:
## Next is No Housing units in tract, Avg Housing Size and Avg Family size where we want % of tract value compared to avg Housing and Family size.

In [53]:
All_CSVs_8 = pd.merge(left = All_CSVs_7, right = groupedStateCountyDP04_0045PEAvgHousingUnits, how = 'inner', on = ['State', 'County'])

In [55]:
All_CSVs_8['%DP04_0045PE-%Occup HU'] =  (All_CSVs_8['DP04_0045PE-%Occup HU']/All_CSVs_8['meanCountyStateAvgNoHU']*100) #.apply(lambda x: '{pct_mean_earnings:.1%}'.format(pct_mean_earnings = x))

In [59]:
## Onto merge 9 here, so SKIPPED 8  )
All_CSVs_9 = pd.merge(left = All_CSVs_8, right = groupedStateCountyDP02_0015EAvgHHSize, how = 'inner', on = ['State', 'County'])

In [61]:
All_CSVs_9['%DP02_0015E-Avg HH Size'] = (All_CSVs_9['DP02_0015E-Avg HH Size'] /All_CSVs_9['meanCountyStateAvgHHSize']*100)

In [62]:
## need merge here
All_CSVs_10 = pd.merge(left = All_CSVs_9, right = groupedStateCountyDP04_0016PEAvgFamSize, how = 'inner', on = ['State', 'County'])

In [63]:
All_CSVs_10['%DP02_0016E-Avg Fam Size'] =  (All_CSVs_10['DP02_0016E-Avg Fam Size']/All_CSVs_10['meanCountyState_AvgFamSize']*100)

In [65]:
All_CSVs_10.describe()

,DP05_0001E-T Popo,DP02_0001E-T HHs,DP02_0002E-T Fam HHs,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0015E-Avg HH Size,DP02_0016E-Avg Fam Size,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0065E-HH-MeanEarnings,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0092E-Median Earning Workers,DP03_0093E-Median Earnings Male FT Workers,DP03_0094E-Median Earnings Female FT Workers,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0001E-T H U,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0006E-T HU,State,County,Tract,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0045PE-%Occup HU,DP04_0046PE-%Owner Occup HU,DP04_0048E-Owner Ave Household size,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP04_0101E-Med Onwer Monthly Mortgage,DP04_0134E-Median Gross Rent,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,DP05_0070PE-%H&L race,AreaLand,crimeStats,ALAND,Popo_Density_Per_Hector,meanCountyStateEarning,%DP03_0065E-HH-MeanEarnings,meanCountyStateWorkerEarnings,%DP03_0092E-Median Earning Workers,meanCountyStateMaleEarnings,%DP03_0093E-Median Earnings Male FT Workers,meanCountyStateFemaleEarnings,%DP03_0094E-Median Earnings Female FT Workers,meanCountyStateOwnerMortgage,%DP04_0101E-Med Onwer Monthly Mortgage,meanCountyStateRent,%DP04_0134E-Median Gross Rent,meanCountyStateHandL_Race,%DP05_0070PE-%H&L race,meanCountyStateAvgNoHU,%DP04_0045PE-%Occup HU,meanCountyStateAvgHHSize,%DP02_0015E-Avg HH Size,meanCountyState_AvgFamSize,%DP02_0016E-Avg Fam Size
count,5287.000000,5287.000000,5287.000000,5277.000000,5277.000000,5275.000000,5274.000000,5277.000000,5274.000000,4658.000000,4658.000000,5286.000000,5286.000000,5287.000000,5287.000000,5287.000000,5287.000000,5287.000000,5280.000000,5280.000000,5280.000000,5280.000000,5280.000000,5280.000000,5280.000000,5277.000000,5277.000000,5277.000000,5277.000000,5261.000000,5277.000000,5277.000000,5277.000000,5274.000000,5267.000000,5230.000000,5229.000000,5284.000000,5284.000000,5284.000000,5274.000000,5149.000000,5076.000000,5287.000000,5278.000000,5190.000000,5271.000000,5287.000000,5287.000000,5287.000000,5287.000000,5278.000000,5278.000000,5278.000000,5278.000000,5287.000000,5277.000000,5287.000000,5158.000000,5277.000000,5277.000000,5186.000000,5186.000000,5186.000000,5186.000000,4887.000000,5219.000000,5287.000000,5287.000000,5287.000000,5287.000000,5287.000000,5287.000000,5287.000000,5287.000000,4.773000e+03,5287.000000,5287.000000,5261.000000,5287.000000,5267.000000,5287.000000,5230.000000,5287.000000,5229.000000,5287.000000,4887.000000,5287.000000,5219.000000,5287.000000,5287.000000,5287.000000,5287.000000,5287.000000,5275.000000,5287.000000,5274.000000
mean,4041.389068,1491.248912,882.965198,17.128141,37.771385,2.793062,3.449287,7.887209,26.277778,5.325676,11.743452,8.869864,6.206810,87.732022,0.915699,66.929090,44.504710,5.081294,7.508144,38.400398,21.408030,9.809564,7.628201,13.781780,0.135966,8.006974,9.876957,11.132727,8.858821,93857.418552,25.192022,3.828672,16.663635,11.855347,40105.655402,57593.012811,49158.702238,58.452555,58.452555,10.461847,14.562173,16.215770,31.860225,1643.839985,90.822016,2.022466,4.296699,1643.839985,24.854549,70.980140,177130.166824,25.599924,0.844259,4.998427,6.413774,1491.248912,41.790752,897.406469,2.986227,4.309797,25.407921,5.799537,6.165310,6.230602,29.762283,2431.559853,1410.989078,6.321978,16.508171,0.673652,0.861320,50.448061,4041.389068,156.740306,1977.228674,1.194380e+06,0.253508,93875.026638,100.000000,40111.710041,100.000000,57585.548596,100.000000,49190.653167,100.000000,2444.202465,100.000000,1411.046275,100.000000,4041.389068,100.000000,1491.248912,100.000000,2.792841,100.000000,3.449067,100.000000
std,2010.676357,865.018421,477.554742,11.222860,16.784513,0.667349,0.555801,5.700843,38.239729,12.736242,18.292207,6.396830,3.366186,8.574061,1.519373,17.026335,25.374551,6.081927,5.412684,19.342522,10.392489,4.582678,5.244613,6.910559,0.414416,6.831105,6.069676,4.768582,10.833275,51592.245771,10.156701,3.919530,14.883091,15.190917,19576.529237,32153.340079,20525.758724,20.441149,20.441149,7.756990,12.152537,23.532272,25.626883,963.112046,7.203690,4.663217,5.053205,963.112046,14.673810,94.760084,225216.777932,29.445262,2.669525,5.965282,8.574816,865.018421,25.449012,724.584822,0.813005,3.531337,7.702969,12.842722,11.542356,10.528142,25.427380,811.065892,508.118513,2.900616,7.649667,1.122762,1.270827,28.669535,2010.676357,1101.420156,4338.415725,1.105674e+07,6.430560,21382.213926,49.148643,8286.155243,43.122900,13248.621844,49.168770,8834.761992,37.433529,476.890087,28.741776,237.713504,30.940062,677.892394,46.175246,345.071086,52.250373,0.239279,22.125325,0.170578,15.311387
min,3.000000,0.000000,0.000000,0.000000,0.000000,1.030000,1.950000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14012.000000,0.000000,0.000000,0.000000,0.000000,2499.000000,17500.000000,12917.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,1.000000,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,347.000000,271.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,2.000000,1.000000,2.209400e+04,0.000900,43193.000000,15.120625,20019.000000,6.737288,31440.000000,17.102366,28291.000000,27.277160,1015.000000,14.186628,640.000000,15.110906,2787.000000,0.052007,831.000000,0.000000,2.090393,34.571277,2.830000,55.571292
25%,2672.500000,920.500000,558.000000,8.600000,25.000000,2.330000,3.080000,4.100000,0.000000,0.000000,0.000000,3.800000,3.900000,84.400000,0.000000,54.500000,23.000000,0.600000,4.100000,23.000000,13.700000,6.900000,4.200000,8.975000,0.000000,3.400000,5.400000,7.900000,1.600000,60023.000000,18.200000,1.000000,4.900000,1.600000,26062.500000,36502.000000,34155.000000,42.200000,42.200000,4.900000,5.000000,0.000000,8.100000,1022.500000,88.300000,0.000000,0.000000,1022.500000,6.000000,37.000000,21600.000000,1.825000,0.000000,0.900000,1.200000,920.500000,21.300000,391.000000,2.440000,1.800000,20.600000,0.000000,0.000000,0.000000,4.900000,1807.000000,1079.500000,4.400000,11.500000,0.000000,0.000000,25.700000,2672.500000,19.000000,196.000000,1.831700e+05,0.006400,82818.577515,68.609003,37075.372038,69.352527,53340.376499,67.043021,46101.365362,72.163095,1948.997590,80.206672,1153.265550,81.262489,3495.173964,68.154139,1267.808000,65.165112,2.657692,84.802493,3.432470,89.770899
50%,3766.000000,1340.000000,810.000000,14.900000,34.900000,2.750000,3.420000,6.500000,13.000000,0.000000,1.650000,7.700000,5.900000,89.800000,0.400000,66.200000,43.000000,2.900000,6.300000,35.300000,21.100000,9.400000,6.600000,12.200000,0.000000,6.200000,9.000000,10.900000,4.900000,80840.000000,24.800000,2.700000,12.600000,5.800000,34720.000000,48828.500000,44583.000000,59.000000,59.000000,8.600000,11.600000,0.000000,30.800000,1466.000000,92.400000,0.000000,3.100000,1466.000000,36.000000,47.000000,80102.000000,11.900000,0.000000,3.000000,3.700000,1340.000000,40.000000,715.000000,2.900000,3.600000,25.200000,0.000000,0.000000,0.800000,25.850000,2420.000000,1333.000000,6.100000,15.600000,0.300000,0.300000,52.800000,3766.000000,46.000000,884.000000,3.827720e+05,0.013400,91992.981283,89.376384,37092.077795,88.905379,54996.506464,89.178187,46711.430418,93.194904,2582.332524,96.838608,1458.220134,95.595992,4188.837594,94.489221,1454.766165,92.443020,2.808501,98.898702,3.454426,99.088202
75%,5077.000000,1867.000000,1114.000000,23.900000,48.600000,3.200000,3.800000,10.300000,42.000000,4.600000,17.600000,12.900000,8.075000,93.400000,1.200000,79.700000,66.000000,7.900000,9.300000,52.600000,28.300000,12.200000,9.700000,17.200000,0.000000,10.400000,13.300000,14.100000,11.500000,108802.000000,31.700000,5.400000,24.200000,15.500000,49163.000000,68225.250000,59432.000000,75.500000,75.500000,13.800000,21.500000,26.800000,50.000000,2036.000000,95.300000,2.700000,6.400000,2036.000000,36.000000,81.000000,232650.000000,43.100000,0.500000,6.900000,8.100000,1867.000000,61.700000,1195.000000,3.450000,6.000000,30.200000,4.100000,6.300000,8.200000,48.300000,2972.000000,1642.000000,8.100000,20.550000,1.000000,1.300000,75.600000,5077.000000,108.000000,2145.500000,8.698300e+05,0.029400,92668.125567,115.622468,39709.205607,120.587789,55259.497305,119.666869,50233.433198,120.339061,2619.822866,115.988802,1535.855293,112.375462,4283.808383,125.621266,1496.191617,126.039932,2.979352,113.464306,3.585185,109.349707
max,28272.000000,12827.000000,6960.000000,100.000000,100.000000,6.540000,7.200000,66.800000,1000.000000,100.000000,100.000000,60.000000,100.000000,100.000000,43.400000,100.000000,100.000000,62.000000,84.900000,100.000000,64.200000,100.000000,62.500000,50.000000,7.100000,100.000000,100.000000,50.000000,88.400000,451457.000000,100.000000,43.800000,100.000000,78.800000,162650.000000,250001.000000,224750.000000,100.000000,100.000000,57.500000,100.000000,100.000000,100.000000,13028.000000,100.000000,100.000000,100.000000,13028.000000,48.000000,510.000000,980900.000000,100.000000,46.900000,58.200000,86.000000,12827.000000,100.000000,8145.000000,8.260000,43.100000,100.000000,100.000000,100.000000,100.000000,100.000000,4001.000000,3501.000000,33.300000,100.000000,24.200000,14.900000,100.000000,28272.000000,61584.000000,116852.000000,6.158485e+08,418.200000,158673.286738,513.768633,65725.214286,338.797413,102325.021505,468.689980,84777.000000,481.145617,3399.796703,269.986598,1954.200000,281.808470,9560.000000,659.973497,2899.500000,857.309977,3.420000,234.346923,4.020000,244.233379

In [66]:
#Creating a dataframe for Population Density so can take these columns out of main dataframe
Popo_Density_Per_Hector_Columns = ['State', 'County', 'Tract', 'Popo_Density_Per_Hector', 'DP05_0001E-T Popo', 'AreaLand', 'ALAND']
Popo_Density_Per_Hector_df = All_CSVs_1[Popo_Density_Per_Hector_Columns]
Popo_Density_Per_Hector_df

      State  County   Tract  Popo_Density_Per_Hector  DP05_0001E-T Popo  AreaLand     ALAND
0        36       5   42902                   0.0021               4205         9   94576.0
1        36       5   33000                   0.0034               5885        20  206129.0
2        36       5   35800                   0.0081               8054        65  651471.0
3        36       5   37100                   0.0044               4322        19  198178.0
4        36       5   38500                   0.0038               4757        18  189195.0
...     ...     ...     ...                      ...                ...       ...       ...
5282     48     139   60212                   0.3500               5542      1945       NaN
5283     48     139   60213                   0.5600               6903      3864       NaN
5284     48     139   60801                   0.5000               7559      3814       NaN
5285     48      29  171301                   0.0400               2787       112       NaN
5286     48     309    2498                   0.0700               5094       352       NaN

[5287 rows x 7 columns]

In [67]:
#Creating a dataframe for Total Population and Total Family size and crime stats so can take these columns out of main dataframe
TotalPopoandTotalFamHHsandCrimeStats = ['State', 'County', 'Tract', 'DP05_0001E-T Popo', 'DP02_0002E-T Fam HHs', 'crimeStats']
TotalPopoandTotalFamHHsandCrimeStats = All_CSVs_1[TotalPopoandTotalFamHHsandCrimeStats]

In [68]:
TotalPopoandTotalFamHHsandCrimeStats[1:5]

   State  County  Tract  DP05_0001E-T Popo  DP02_0002E-T Fam HHs  crimeStats
1     36       5  33000               5885                  1433        2490
2     36       5  35800               8054                  1885        1667
3     36       5  37100               4322                   888        2504
4     36       5  38500               4757                  1028        3443

In [69]:
All_CSVs_10['AreaLand']

0          9
1         20
2         65
3         19
4         18
        ...
5282    1945
5283    3864
5284    3814
5285     112
5286     352
Name: AreaLand, Length: 5287, dtype: int64

In [70]:
All_CSVs_10['%DP04_0101E-Med Onwer Monthly Mortgage']

0       148.366778
1              NaN
2       115.169251
3        94.073286
4       112.430046
           ...
5282     92.813918
5283     86.346445
5284    120.839637
5285    100.000000
5286    100.000000
Name: %DP04_0101E-Med Onwer Monthly Mortgage, Length: 5287, dtype: float64

In [71]:
#######REMOVING ROWS  

## Removing population density columns after creating subset dataframe "Popo_Density_Per_Hector"
## Removing MeanEarning columns after creating for DP03_0065E % calcualtion
All_CSVs_11 = All_CSVs_10
All_CSVs_11.drop('Popo_Density_Per_Hector', inplace = True, axis=1)
All_CSVs_11.drop('AreaLand',inplace = True, axis=1)
All_CSVs_11.drop('ALAND', inplace = True, axis=1)

## Removing total population and total family households after creating a subset dataframe "TotalPopoandTotalFamHHs"
#'DP05_0001E-T Popo', 'DP02_0002E-T Fam HHs'
All_CSVs_11.drop('DP05_0001E-T Popo', inplace = True,  axis=1)
All_CSVs_11.drop('DP02_0002E-T Fam HHs', inplace = True,  axis=1)



#removing DP columns which were estimates and where mean was used to calculate % mean for state county combination 
All_CSVs_11.drop('DP03_0065E-HH-MeanEarnings', inplace = True,  axis=1)
All_CSVs_11.drop('meanCountyStateEarning', inplace = True,  axis=1)
All_CSVs_11.drop('DP03_0092E-Median Earning Workers', inplace = True,  axis=1)
All_CSVs_11.drop('meanCountyStateWorkerEarnings', inplace = True,  axis=1)
All_CSVs_11.drop('DP03_0093E-Median Earnings Male FT Workers', inplace = True,  axis=1)
All_CSVs_11.drop('meanCountyStateMaleEarnings', inplace = True,  axis=1)
All_CSVs_11.drop('DP03_0094E-Median Earnings Female FT Workers', inplace = True,  axis=1)
All_CSVs_11.drop('meanCountyStateFemaleEarnings', inplace = True,  axis=1)
All_CSVs_11.drop('DP04_0101E-Med Onwer Monthly Mortgage', inplace = True,  axis=1)
All_CSVs_11.drop('meanCountyStateOwnerMortgage', inplace = True,  axis=1)
All_CSVs_11.drop('DP04_0134E-Median Gross Rent', inplace = True,  axis=1)
All_CSVs_11.drop('meanCountyStateRent', inplace = True,  axis=1)
All_CSVs_11.drop('DP05_0070PE-%H&L race', inplace = True,  axis=1)
All_CSVs_11.drop('meanCountyStateHandL_Race', inplace = True,  axis=1)

All_CSVs_11.drop('DP04_0006E-T HU', inplace = True,  axis=1)## remove DP04_0006E-T HU - Another Total HU - don't need
All_CSVs_11.drop('DP04_0001E-T H U', inplace = True,  axis=1)
#Remove DP04_0045PE-%Occup HU and DP02_0001E-T HHs now that %DP04_0045PE-%Occup HU exists 
All_CSVs_11.drop('DP04_0045PE-%Occup HU', inplace = True,  axis=1)
All_CSVs_11.drop('DP02_0001E-T HHs', inplace = True,  axis=1)
#DP04_0048E-Owner Ave Household size - don't understand this output
All_CSVs_11.drop('DP04_0048E-Owner Ave Household size', inplace = True,  axis=1)

## DP02_0015E and DP02_0016E Avg HH Size and Avg Fam Size removing because now have % of HH and Family as per state and county
All_CSVs_11.drop('DP02_0015E-Avg HH Size', inplace = True,  axis=1)
All_CSVs_11.drop('DP02_0016E-Avg Fam Size', inplace = True,  axis=1)

In [72]:
# drop meanCountyStateAvgHHSize and meanCountyState_AvgFamSize
All_CSVs_11.drop('meanCountyStateAvgHHSize', inplace = True,  axis=1)
All_CSVs_11.drop('meanCountyState_AvgFamSize', inplace = True,  axis=1)

In [73]:
All_CSVs_11.dtypes

NAME                                              object
DP02_0008PE-%F-led HHs No H                      float64
DP02_0010PE-% Non-Fam HHs                        float64
DP02_0022PE-%Non Rel in Hs                       float64
DP02_0038E-per1000-F-U-RecentPreg                float64
DP02_0046PE-%GPwParent&Gc1-2yrs                  float64
DP02_0048PE--%GPwParent&Gc>5yrs                  float64
DP02_0060PE-%NoSchDiploma                        float64
DP02_0063PE-%AssDeg                              float64
DP02_0079PE-% SameHouse_1YrAgo                   float64
DP02_0085PE-%LivAbroad1YrAgo                     float64
DP02_0088PE-%BornUS                              float64
DP02_0112PE-HomeLangNotEng                       float64
DP02_0134PE-%IrishAnc                            float64
DP03_0009PE-%Unemploy                            float64
DP03_0027PE-%WorkingMgt,Bus,Sc,Arts              float64
DP03_0028PE%WorkingService                       float64
DP03_0037PE-Retail                               float64
DP03_0040PE-%Fin&Ins                             float64
DP03_0041PE-%ProfSc,Mgt,Admin                    float64
DP03_0050PE-%UnpaidFamilyWk                      float64
DP03_0052PE-Inc<10k                              float64
DP03_0054PE-Inc15-24k                            float64
DP03_0058PE-Inc75-99k                            float64
DP03_0061PE-Inc200k>                             float64
DP03_0066PE-%HHsWithSocSec                       float64
DP03_0072PE-%HH Inc with Cash public Ass         float64
DP03_0074PE-%HH Inc with Food Stamps SNAP        float64
DP03_0085PE-%Families Inc>200k                   float64
DP03_0097PE-%PHI-Priv                            float64
DP03_0098PE-%PHI-Pub                             float64
DP03_0099PE-No PHI                               float64
DP03_0119PE-% Fam <Pov                           float64
DP03_0121PE-%Fam with child U18&U5 <pov          float64
DP03_0126PE-%F-Led Families with u18 <pov        float64
DP04_0002PE-%Occ H U                             float64
DP04_0004E-%Ow Vac Rate                          float64
DP04_0005E-%Rn Vac Rate                          float64
State                                              int64
County                                             int64
Tract                                              int64
DP04_0013PE-%20+HU                               float64
DP04_0017PE-%Built2014+                          float64
DP04_0029PE-%2rooms_only_HU                      float64
DP04_0039PE-Zero bedrooms                        float64
DP04_0046PE-%Owner Occup HU                      float64
DP04_0049E-Renter Ave Household size             float64
DP04_0051PE-%moved since 2017+                   float64
DP04_0054PE-%moved 2000 to 2009                  float64
DP04_0082PE-%Value 50-99k                        float64
DP04_0083PE-%Value 100-149k                      float64
DP04_0084PE-%Value 150-199k                      float64
DP04_0087PE-%Value 500k-1m                       float64
DP05_0005PE-%under 5 yrs                         float64
DP05_0023PE-%62 yrs+                             float64
DP05_0058PE-% w & B or AM                        float64
DP05_0061PE-%White & Asian                       float64
DP05_0064PE-%White with others                   float64
crimeStats                                         int64
crime                                             object
%DP03_0065E-HH-MeanEarnings                      float64
%DP03_0092E-Median Earning Workers               float64
%DP03_0093E-Median Earnings Male FT Workers      float64
%DP03_0094E-Median Earnings Female FT Workers    float64
%DP04_0101E-Med Onwer Monthly Mortgage           float64
%DP04_0134E-Median Gross Rent                    float64
%DP05_0070PE-%H&L race                           float64
meanCountyStateAvgNoHU                           float64
%DP04_0045PE-%Occup HU                           float64
%DP02_0015E-Avg HH Size                          float64
%DP02_0016E-Avg Fam Size                         float64
dtype: object

In [74]:
All_CSVs_11.describe()

,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,State,County,Tract,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0046PE-%Owner Occup HU,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,crimeStats,%DP03_0065E-HH-MeanEarnings,%DP03_0092E-Median Earning Workers,%DP03_0093E-Median Earnings Male FT Workers,%DP03_0094E-Median Earnings Female FT Workers,%DP04_0101E-Med Onwer Monthly Mortgage,%DP04_0134E-Median Gross Rent,%DP05_0070PE-%H&L race,meanCountyStateAvgNoHU,%DP04_0045PE-%Occup HU,%DP02_0015E-Avg HH Size,%DP02_0016E-Avg Fam Size
count,5277.000000,5277.000000,5277.000000,5274.000000,4658.000000,4658.000000,5286.000000,5286.000000,5287.000000,5287.000000,5287.000000,5287.000000,5287.000000,5280.000000,5280.000000,5280.000000,5280.000000,5280.000000,5280.000000,5280.000000,5277.000000,5277.000000,5277.000000,5277.000000,5277.000000,5277.000000,5277.000000,5274.000000,5284.000000,5284.000000,5284.000000,5274.000000,5149.000000,5076.000000,5278.000000,5190.000000,5271.000000,5287.000000,5287.000000,5287.000000,5278.000000,5278.000000,5278.000000,5278.000000,5277.000000,5158.000000,5277.000000,5277.000000,5186.000000,5186.000000,5186.000000,5186.000000,5287.000000,5287.000000,5287.000000,5287.000000,5287.000000,5287.000000,5261.000000,5267.000000,5230.000000,5229.000000,4887.000000,5219.000000,5287.000000,5287.000000,5287.000000,5275.000000,5274.000000
mean,17.128141,37.771385,7.887209,26.277778,5.325676,11.743452,8.869864,6.206810,87.732022,0.915699,66.929090,44.504710,5.081294,7.508144,38.400398,21.408030,9.809564,7.628201,13.781780,0.135966,8.006974,9.876957,11.132727,8.858821,25.192022,3.828672,16.663635,11.855347,58.452555,58.452555,10.461847,14.562173,16.215770,31.860225,90.822016,2.022466,4.296699,24.854549,70.980140,177130.166824,25.599924,0.844259,4.998427,6.413774,41.790752,2.986227,4.309797,25.407921,5.799537,6.165310,6.230602,29.762283,6.321978,16.508171,0.673652,0.861320,50.448061,1977.228674,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,1491.248912,100.000000,100.000000,100.000000
std,11.222860,16.784513,5.700843,38.239729,12.736242,18.292207,6.396830,3.366186,8.574061,1.519373,17.026335,25.374551,6.081927,5.412684,19.342522,10.392489,4.582678,5.244613,6.910559,0.414416,6.831105,6.069676,4.768582,10.833275,10.156701,3.919530,14.883091,15.190917,20.441149,20.441149,7.756990,12.152537,23.532272,25.626883,7.203690,4.663217,5.053205,14.673810,94.760084,225216.777932,29.445262,2.669525,5.965282,8.574816,25.449012,0.813005,3.531337,7.702969,12.842722,11.542356,10.528142,25.427380,2.900616,7.649667,1.122762,1.270827,28.669535,4338.415725,49.148643,43.122900,49.168770,37.433529,28.741776,30.940062,46.175246,345.071086,52.250373,22.125325,15.311387
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,1.000000,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,15.120625,6.737288,17.102366,27.277160,14.186628,15.110906,0.052007,831.000000,0.000000,34.571277,55.571292
25%,8.600000,25.000000,4.100000,0.000000,0.000000,0.000000,3.800000,3.900000,84.400000,0.000000,54.500000,23.000000,0.600000,4.100000,23.000000,13.700000,6.900000,4.200000,8.975000,0.000000,3.400000,5.400000,7.900000,1.600000,18.200000,1.000000,4.900000,1.600000,42.200000,42.200000,4.900000,5.000000,0.000000,8.100000,88.300000,0.000000,0.000000,6.000000,37.000000,21600.000000,1.825000,0.000000,0.900000,1.200000,21.300000,2.440000,1.800000,20.600000,0.000000,0.000000,0.000000,4.900000,4.400000,11.500000,0.000000,0.000000,25.700000,196.000000,68.609003,69.352527,67.043021,72.163095,80.206672,81.262489,68.154139,1267.808000,65.165112,84.802493,89.770899
50%,14.900000,34.900000,6.500000,13.000000,0.000000,1.650000,7.700000,5.900000,89.800000,0.400000,66.200000,43.000000,2.900000,6.300000,35.300000,21.100000,9.400000,6.600000,12.200000,0.000000,6.200000,9.000000,10.900000,4.900000,24.800000,2.700000,12.600000,5.800000,59.000000,59.000000,8.600000,11.600000,0.000000,30.800000,92.400000,0.000000,3.100000,36.000000,47.000000,80102.000000,11.900000,0.000000,3.000000,3.700000,40.000000,2.900000,3.600000,25.200000,0.000000,0.000000,0.800000,25.850000,6.100000,15.600000,0.300000,0.300000,52.800000,884.000000,89.376384,88.905379,89.178187,93.194904,96.838608,95.595992,94.489221,1454.766165,92.443020,98.898702,99.088202
75%,23.900000,48.600000,10.300000,42.000000,4.600000,17.600000,12.900000,8.075000,93.400000,1.200000,79.700000,66.000000,7.900000,9.300000,52.600000,28.300000,12.200000,9.700000,17.200000,0.000000,10.400000,13.300000,14.100000,11.500000,31.700000,5.400000,24.200000,15.500000,75.500000,75.500000,13.800000,21.500000,26.800000,50.000000,95.300000,2.700000,6.400000,36.000000,81.000000,232650.000000,43.100000,0.500000,6.900000,8.100000,61.700000,3.450000,6.000000,30.200000,4.100000,6.300000,8.200000,48.300000,8.100000,20.550000,1.000000,1.300000,75.600000,2145.500000,115.622468,120.587789,119.666869,120.339061,115.988802,112.375462,125.621266,1496.191617,126.039932,113.464306,109.349707
max,100.000000,100.000000,66.800000,1000.000000,100.000000,100.000000,60.000000,100.000000,100.000000,43.400000,100.000000,100.000000,62.000000,84.900000,100.000000,64.200000,100.000000,62.500000,50.000000,7.100000,100.000000,100.000000,50.000000,88.400000,100.000000,43.800000,100.000000,78.800000,100.000000,100.000000,57.500000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,48.000000,510.000000,980900.000000,100.000000,46.900000,58.200000,86.000000,100.000000,8.260000,43.100000,100.000000,100.000000,100.000000,100.000000,100.000000,33.300000,100.000000,24.200000,14.900000,100.000000,116852.000000,513.768633,338.797413,468.689980,481.145617,269.986598,281.808470,659.973497,2899.500000,857.309977,234.346923,244.233379

In [75]:
#census_tract_Texas['COUNTYFP'] = census_tract_Texas['COUNTYFP'].apply(lambda x: '{0:0>3}'.format(x)).astype(str)
All_CSVs_11['Countyfp'] = All_CSVs_11['County'].apply(lambda x: '{0:0>3}'.format(x)).astype(str)

In [76]:
All_CSVs_11['Tractce'] = All_CSVs_11['Tract'].apply(lambda x: '{0:0>6}'.format(x)).astype(str)

In [77]:
All_CSVs_11['Statefp'] = All_CSVs_11['State'].apply(lambda x: '{0:0>2}'.format(x)).astype(str)

In [78]:
All_CSVs_11['Tractce']

0       042902
1       033000
2       035800
3       037100
4       038500
         ...
5282    060212
5283    060213
5284    060801
5285    171301
5286    002498
Name: Tractce, Length: 5287, dtype: object

In [79]:
All_CSVs_11['Statefp'].unique() # for various states: CA (06), Texas (48), NY (36), Illinois (17) Maryland (24)

array(['36', '24', '17', '06', '48'], dtype=object)

In [80]:
All_CSVs_11.drop('State', inplace = True,  axis=1)
All_CSVs_11.drop('County', inplace = True,  axis=1)
All_CSVs_11.drop('Tract', inplace = True,  axis=1)

In [81]:
## Save final dataframe to a csv file
All_CSVs_11.to_csv("All_CSVs_Cleaned_and_no_shape_Mar8th.csv")

In [82]:
## Save total popo and total no of family household dataframe to a csv file
TotalPopoandTotalFamHHsandCrimeStats.to_csv("TotalPopoandTotalFamHHs_Mar8th.csv")

In [83]:
## Save Popo_Density_Per_Hector dataframe to a csv file
Popo_Density_Per_Hector_df.to_csv("Popo_Density_Per_Hector_Mar8th.csv")

In [71]:
All_CSVs_11['Statefp'].unique()

array(['36', '24', '17', '06', '48'], dtype=object)

In [84]:
## NYC_CSV__Dec9th_before.csv
NYC_CSV_Cleaned_and_no_shape_Mar6th = All_CSVs_11[All_CSVs_11['Statefp']=='36']
NYC_CSV_Cleaned_and_no_shape_Mar6th.to_csv("NYC_CSV_Cleaned_and_no_shape_Mar8th.csv")

In [85]:
NYC_CSV_Cleaned_and_no_shape_Mar6th[1:2]

,NAME,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0046PE-%Owner Occup HU,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,crimeStats,crime,%DP03_0065E-HH-MeanEarnings,%DP03_0092E-Median Earning Workers,%DP03_0093E-Median Earnings Male FT Workers,%DP03_0094E-Median Earnings Female FT Workers,%DP04_0101E-Med Onwer Monthly Mortgage,%DP04_0134E-Median Gross Rent,%DP05_0070PE-%H&L race,meanCountyStateAvgNoHU,%DP04_0045PE-%Occup HU,%DP02_0015E-Avg HH Size,%DP02_0016E-Avg Fam Size,Countyfp,Tractce,Statefp
1,"Census Tract 330, Bronx County, New York",12.3,32.7,4.6,104.0,0.0,0.0,6.4,7.7,90.4,0.0,45.5,73.8,1.7,14.7,23.4,26.5,17.7,6.6,9.3,0.0,10.1,12.8,7.9,0.0,18.0,5.1,35.5,0.0,38.0,38.0,17.3,18.1,11.5,76.0,95.1,0.0,3.5,66.9,0.9,1.2,10.0,4.9,3.32,1.6,46.6,18.1,0.0,0.0,5.7,6.9,15.8,0.0,0.0,50.0,2490,high,82.128499,91.666243,87.352318,80.463775,NaN,99.841471,137.37776,1496.191617,142.294608,97.118208,97.748479,005,033000,36

In [86]:
print("shape NYC:", NYC_CSV_Cleaned_and_no_shape_Mar6th.shape)

shape NYC: (2140, 71)

In [88]:
LA_and_SF_CSV_Cleaned_and_no_shape_Mar6th = All_CSVs_11[All_CSVs_11['Statefp']=='06']
LA_and_SF_CSV_Cleaned_and_no_shape_Mar6th.to_csv("LA_and_SF_CSV_Cleaned_and_no_shape_Mar8th.csv")
LA_and_SF_CSV_Cleaned_and_no_shape_Mar6th[1:2]

,NAME,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0046PE-%Owner Occup HU,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,crimeStats,crime,%DP03_0065E-HH-MeanEarnings,%DP03_0092E-Median Earning Workers,%DP03_0093E-Median Earnings Male FT Workers,%DP03_0094E-Median Earnings Female FT Workers,%DP04_0101E-Med Onwer Monthly Mortgage,%DP04_0134E-Median Gross Rent,%DP05_0070PE-%H&L race,meanCountyStateAvgNoHU,%DP04_0045PE-%Occup HU,%DP02_0015E-Avg HH Size,%DP02_0016E-Avg Fam Size,Countyfp,Tractce,Statefp
3242,"Census Tract 5501, Los Angeles County, California",12.6,15.9,4.9,46.0,2.0,3.3,10.1,7.3,97.5,0.2,64.1,74.0,0.8,4.6,28.7,20.0,12.4,5.8,4.2,0.0,3.8,5.4,17.0,5.6,23.8,2.7,5.5,4.2,73.6,73.6,3.0,7.5,5.4,6.3,96.5,3.7,0.0,3.5,0.0,0.4,2.1,81.8,3.89,0.5,29.5,0.0,0.0,0.0,9.4,6.6,14.9,0.0,0.9,49.0,1,low,91.633449,85.201482,76.66487,72.735944,74.119037,81.583207,177.63878,1454.766165,129.642828,132.579168,119.101258,037,550100,06

In [89]:
Chicago_CSV_Cleaned_and_no_shape_Mar6th = All_CSVs_11[All_CSVs_11['Statefp']=='17'] 
Chicago_CSV_Cleaned_and_no_shape_Mar6th.to_csv("Chicago_CSV_Cleaned_and_no_shape_Mar8th.csv")
Chicago_CSV_Cleaned_and_no_shape_Mar6th[1:2]

,NAME,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0046PE-%Owner Occup HU,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,crimeStats,crime,%DP03_0065E-HH-MeanEarnings,%DP03_0092E-Median Earning Workers,%DP03_0093E-Median Earnings Male FT Workers,%DP03_0094E-Median Earnings Female FT Workers,%DP04_0101E-Med Onwer Monthly Mortgage,%DP04_0134E-Median Gross Rent,%DP05_0070PE-%H&L race,meanCountyStateAvgNoHU,%DP04_0045PE-%Occup HU,%DP02_0015E-Avg HH Size,%DP02_0016E-Avg Fam Size,Countyfp,Tractce,Statefp
2396,"Census Tract 4205, Cook County, Illinois",23.8,53.8,4.0,0.0,0.0,23.5,10.1,14.4,92.9,0.0,93.5,14.4,0.0,25.8,41.1,30.8,9.0,3.3,22.9,1.0,16.8,15.4,15.4,0.0,41.3,6.1,30.4,0.0,45.0,45.0,7.5,11.4,25.8,25.3,70.3,14.7,12.5,37.1,4.5,2.2,2.5,18.9,1.8,1.3,24.0,2.6,21.2,39.1,0.0,5.2,24.2,1.0,0.0,1.0,245,high,54.747378,79.208915,91.896614,63.978582,61.826654,85.345923,47.465449,1347.949112,59.275235,78.263386,91.529148,031,420500,17

In [91]:
Baltimore_CSV_Cleaned_and_no_shape_Mar6th = All_CSVs_11[All_CSVs_11['Statefp']=='24']
Baltimore_CSV_Cleaned_and_no_shape_Mar6th.to_csv("Baltimore_CSV_Cleaned_and_no_shape_Mar8h.csv")
Baltimore_CSV_Cleaned_and_no_shape_Mar6th[1:2]

,NAME,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0046PE-%Owner Occup HU,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,crimeStats,crime,%DP03_0065E-HH-MeanEarnings,%DP03_0092E-Median Earning Workers,%DP03_0093E-Median Earnings Male FT Workers,%DP03_0094E-Median Earnings Female FT Workers,%DP04_0101E-Med Onwer Monthly Mortgage,%DP04_0134E-Median Gross Rent,%DP05_0070PE-%H&L race,meanCountyStateAvgNoHU,%DP04_0045PE-%Occup HU,%DP02_0015E-Avg HH Size,%DP02_0016E-Avg Fam Size,Countyfp,Tractce,Statefp
2141,"Census Tract 7501.01, Anne Arundel County, Mar...",18.4,40.1,8.3,18.0,0.0,21.0,8.1,6.9,92.3,1.4,90.3,10.7,6.7,6.9,26.3,25.8,11.3,3.1,14.8,0.0,6.9,9.6,15.6,2.0,32.6,3.1,16.7,1.1,60.2,60.2,6.2,12.3,0.0,25.4,95.2,0.6,5.3,0.0,0.0,0.4,1.4,72.3,2.75,1.3,38.8,13.1,11.1,18.6,0.8,7.0,13.7,4.8,0.9,72.3,26,low,76.097192,82.166132,88.315312,72.666925,80.672269,79.921154,89.867749,1732.375,89.81889,99.089253,107.320813,003,750101,24

In [92]:
Dallas_CSV_Cleaned_and_no_shape_Mar6th = All_CSVs_11[All_CSVs_11['Statefp']=='48']
Dallas_CSV_Cleaned_and_no_shape_Mar6th.to_csv("Dallas_CSV_Cleaned_and_no_shape_Mar8th.csv")
Dallas_CSV_Cleaned_and_no_shape_Mar6th[1:2]

,NAME,DP02_0008PE-%F-led HHs No H,DP02_0010PE-% Non-Fam HHs,DP02_0022PE-%Non Rel in Hs,DP02_0038E-per1000-F-U-RecentPreg,DP02_0046PE-%GPwParent&Gc1-2yrs,DP02_0048PE--%GPwParent&Gc>5yrs,DP02_0060PE-%NoSchDiploma,DP02_0063PE-%AssDeg,DP02_0079PE-% SameHouse_1YrAgo,DP02_0085PE-%LivAbroad1YrAgo,DP02_0088PE-%BornUS,DP02_0112PE-HomeLangNotEng,DP02_0134PE-%IrishAnc,DP03_0009PE-%Unemploy,"DP03_0027PE-%WorkingMgt,Bus,Sc,Arts",DP03_0028PE%WorkingService,DP03_0037PE-Retail,DP03_0040PE-%Fin&Ins,"DP03_0041PE-%ProfSc,Mgt,Admin",DP03_0050PE-%UnpaidFamilyWk,DP03_0052PE-Inc<10k,DP03_0054PE-Inc15-24k,DP03_0058PE-Inc75-99k,DP03_0061PE-Inc200k>,DP03_0066PE-%HHsWithSocSec,DP03_0072PE-%HH Inc with Cash public Ass,DP03_0074PE-%HH Inc with Food Stamps SNAP,DP03_0085PE-%Families Inc>200k,DP03_0097PE-%PHI-Priv,DP03_0098PE-%PHI-Pub,DP03_0099PE-No PHI,DP03_0119PE-% Fam <Pov,DP03_0121PE-%Fam with child U18&U5 <pov,DP03_0126PE-%F-Led Families with u18 <pov,DP04_0002PE-%Occ H U,DP04_0004E-%Ow Vac Rate,DP04_0005E-%Rn Vac Rate,DP04_0013PE-%20+HU,DP04_0017PE-%Built2014+,DP04_0029PE-%2rooms_only_HU,DP04_0039PE-Zero bedrooms,DP04_0046PE-%Owner Occup HU,DP04_0049E-Renter Ave Household size,DP04_0051PE-%moved since 2017+,DP04_0054PE-%moved 2000 to 2009,DP04_0082PE-%Value 50-99k,DP04_0083PE-%Value 100-149k,DP04_0084PE-%Value 150-199k,DP04_0087PE-%Value 500k-1m,DP05_0005PE-%under 5 yrs,DP05_0023PE-%62 yrs+,DP05_0058PE-% w & B or AM,DP05_0061PE-%White & Asian,DP05_0064PE-%White with others,crimeStats,crime,%DP03_0065E-HH-MeanEarnings,%DP03_0092E-Median Earning Workers,%DP03_0093E-Median Earnings Male FT Workers,%DP03_0094E-Median Earnings Female FT Workers,%DP04_0101E-Med Onwer Monthly Mortgage,%DP04_0134E-Median Gross Rent,%DP05_0070PE-%H&L race,meanCountyStateAvgNoHU,%DP04_0045PE-%Occup HU,%DP02_0015E-Avg HH Size,%DP02_0016E-Avg Fam Size,Countyfp,Tractce,Statefp
4774,"Census Tract 178.13, Dallas County, Texas",23.9,29.0,8.1,160.0,0.0,0.0,12.4,6.8,71.5,1.2,77.8,38.2,3.3,5.4,26.1,12.7,16.7,7.3,13.3,0.0,1.9,7.7,12.0,1.4,10.7,1.2,16.8,1.9,53.0,53.0,26.5,7.1,12.8,6.8,88.7,12.7,9.0,16.7,0.4,2.7,4.6,19.5,3.06,11.1,9.6,25.0,53.4,19.3,0.0,9.1,7.2,1.2,1.4,52.4,1,low,67.301566,82.371861,70.770297,79.141912,73.756212,91.566075,141.579924,1747.194379,139.709699,100.765491,94.082194,113,017813,48